//! This code was AUTOGENERATED using the Codama library.

pub mod authority_updated;
pub mod authority_update_proposed;
pub mod config_initialized;
pub mod config_updated;
pub mod listing_duration_changed;
pub mod location_created;
pub mod location_removed;
pub mod region_claimed;
pub mod region_created;
pub mod region_proposal_passed;
pub mod region_proposal_rejected;
pub mod region_proposed;
pub mod region_state_cleared;
pub mod region_tax_changed;
pub mod resignation_initiated;
pub mod voted_on_region_proposal;
pub mod voting_token_unlocked;

