//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "BuyShares")]
pub struct BuySharesGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub hub_id: U64,
    pub amount: U32,
    pub max_cost: U64,
}

impl TryFrom<crate::instructions::postgres::BuySharesRow> for BuySharesGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::BuySharesRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            hub_id: carbon_core::graphql::primitives::U64(*row.hub_id),
            amount: carbon_core::graphql::primitives::U32((*row.amount) as u32),
            max_cost: carbon_core::graphql::primitives::U64(*row.max_cost),
        })
    }
}
