//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DelistShares")]
pub struct DelistSharesGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub hub_id: U64,
}

impl TryFrom<crate::instructions::postgres::DelistSharesRow> for DelistSharesGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::DelistSharesRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            hub_id: carbon_core::graphql::primitives::U64(*row.hub_id),
        })
    }
}
