//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::ListingStatus;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct DocumentsConfirmedEvent {
    pub listing_id: u64,
    pub lawyer: Pubkey,
    pub approve: bool,
    /// The document set the verdict rules on.
    pub documents_hash: [u8; 32],
    /// Where the verdict left the sale.
    pub status: ListingStatus,
}

impl DocumentsConfirmedEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[87, 82, 112, 130, 170, 46, 231, 98] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
