//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::AccessPermission;
use crate::types::Role;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct RoleAccount {
    pub user: Pubkey,
    pub role: Role,
    pub permission: AccessPermission,
    /// Who paid the account's rent (the assigning admin); every teardown
    /// refunds them, whoever triggers it.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl RoleAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[142, 236, 135, 197, 214, 3, 244, 226] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
