//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Compliance status for a (user, role) assignment, set by an admin after
/// off-chain KYC/AML. Only the marketplace's investor-fund calls (listing,
/// buying, offers, share transfers, lawyer case work) require this flag on
/// top of the role; every other instruction checks role possession alone.
/// Later it'll be driven by a SAS attestation instead of a manual toggle.
/// 
/// Do not reorder the variants: the serialized `RoleAccount.permission`
/// stores the variant index, so a reorder flips every stored status.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub enum AccessPermission {
    Compliant,
    Revoked,
}

