//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct CancelledFeesSettled {
    pub listing_id: u64,
    pub payment_mint: Pubkey,
    pub lawyer_paid: u64,
    pub treasury_paid: u64,
}

