//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct PropertyListed {
    pub listing_id: u64,
    pub developer: Pubkey,
    pub region_id: u16,
    pub share_price: u64,
    pub share_amount: u32,
    pub listing_expiry: i64,
}

