//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SpvCaseClaimed {
    pub listing_id: u64,
    pub round: u64,
    pub lawyer: Pubkey,
    pub costs: u64,
    pub expiry: i64,
}

