//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// The running SPV lawyer election. Any eligible lawyer may stand; the first
/// candidacy opens the voting window and shareholders vote among the
/// candidates. A round that elects nobody simply reopens: rounds repeat
/// until a lawyer is engaged or the legal process expires into its timeout
/// exit. One round at a time per listing.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct SpvElection {
    /// When voting closes; zero while no round is running.
    pub expiry: i64,
    /// Candidates standing in the current round.
    pub candidate_count: u32,
    /// Round number, monotonic per listing. Candidacies and vote records are
    /// keyed by it, so nothing stale can count toward a later round.
    pub round: u64,
}

