//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::AccessPermissionGraphQL;
use crate::types::graphql::RoleGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RoleAccount")]
pub struct RoleAccountGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub user: Pubkey,
    pub role: RoleGraphQL,
    pub permission: AccessPermissionGraphQL,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::RoleAccountRow> for RoleAccountGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::RoleAccountRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            user: carbon_core::graphql::primitives::Pubkey(row.user.0),
            role: row.role.0.into(),
            permission: row.permission.0.into(),
            rent_payer: carbon_core::graphql::primitives::Pubkey(row.rent_payer.0),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
