//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct DelistShares {
    pub hub_id: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DelistSharesInstructionAccounts {
    pub seller: solana_pubkey::Pubkey,
    pub holding: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl DelistShares {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[75, 11, 92, 6, 15, 186, 201, 253] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for DelistShares {
    type ArrangedAccounts = DelistSharesInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let seller = next_account(&mut iter)?;
        let holding = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(DelistSharesInstructionAccounts {
            seller,
            holding,
            listing,
            remaining: remaining.to_vec(),
        })
    }
}
