//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Faucet {
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FaucetInstructionAccounts {
    pub caller: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub stable_mint: solana_pubkey::Pubkey,
    pub receipt: solana_pubkey::Pubkey,
    pub caller_stable: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Faucet {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[0, 98, 59, 30, 144, 142, 113, 12] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for Faucet {
    type ArrangedAccounts = FaucetInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let caller = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let stable_mint = next_account(&mut iter)?;
        let receipt = next_account(&mut iter)?;
        let caller_stable = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(FaucetInstructionAccounts {
            caller,
            config,
            stable_mint,
            receipt,
            caller_stable,
            token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
