//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::RealxhubDecoder;
#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod buy_shares;
pub mod claim_income;
pub mod create_hub;
pub mod delist_shares;
pub mod faucet;
pub mod initialize;
pub mod list_shares;
pub mod record_sale;
pub mod cpi_event;

pub use self::buy_shares::*;
pub use self::claim_income::*;
pub use self::create_hub::*;
pub use self::delist_shares::*;
pub use self::faucet::*;
pub use self::initialize::*;
pub use self::list_shares::*;
pub use self::record_sale::*;
pub use self::cpi_event::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum RealxhubInstruction {
    BuyShares(BuyShares),
    ClaimIncome(ClaimIncome),
    CreateHub(CreateHub),
    DelistShares(DelistShares),
    Faucet(Faucet),
    Initialize(Initialize),
    ListShares(ListShares),
    RecordSale(RecordSale),
    // Anchor CPI Event Instruction
    CpiEvent(CpiEvent)
}

impl carbon_core::instruction::InstructionDecoder<'_> for RealxhubDecoder {
    type InstructionType = RealxhubInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = buy_shares::BuyShares::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::BuyShares(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_income::ClaimIncome::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::ClaimIncome(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_hub::CreateHub::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::CreateHub(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = delist_shares::DelistShares::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::DelistShares(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = faucet::Faucet::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::Faucet(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = list_shares::ListShares::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::ListShares(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = record_sale::RecordSale::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::RecordSale(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: RealxhubInstruction::CpiEvent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
