//! This code was AUTOGENERATED using the Codama library.
pub mod buy_shares_row;
pub mod claim_income_row;
pub mod create_hub_row;
pub mod delist_shares_row;
pub mod faucet_row;
pub mod initialize_row;
pub mod list_shares_row;
pub mod record_sale_row;
pub mod cpi_event_row;

pub use self::buy_shares_row::*;
pub use self::claim_income_row::*;
pub use self::create_hub_row::*;
pub use self::delist_shares_row::*;
pub use self::faucet_row::*;
pub use self::initialize_row::*;
pub use self::list_shares_row::*;
pub use self::record_sale_row::*;
pub use self::cpi_event_row::*;

use super::RealxhubInstruction;

pub struct RealxhubInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for RealxhubInstructionsMigration {
    fn app(&self) -> &str {
        "realxhub"
    }

    fn name(&self) -> &str {
        "realxhub_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(BuySharesMigrationOperation),
            Box::new(ClaimIncomeMigrationOperation),
            Box::new(CreateHubMigrationOperation),
            Box::new(DelistSharesMigrationOperation),
            Box::new(FaucetMigrationOperation),
            Box::new(InitializeMigrationOperation),
            Box::new(ListSharesMigrationOperation),
            Box::new(RecordSaleMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct RealxhubInstructionWithMetadata(pub RealxhubInstruction, pub carbon_core::instruction::InstructionMetadata);

impl From<(RealxhubInstruction, carbon_core::instruction::InstructionMetadata)> for RealxhubInstructionWithMetadata {
    fn from(value: (RealxhubInstruction, carbon_core::instruction::InstructionMetadata)) -> Self {
        RealxhubInstructionWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RealxhubInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RealxhubInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            RealxhubInstruction::BuyShares(instruction) => {
                let row = buy_shares_row::BuySharesRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::ClaimIncome(instruction) => {
                let row = claim_income_row::ClaimIncomeRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::CreateHub(instruction) => {
                let row = create_hub_row::CreateHubRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::DelistShares(instruction) => {
                let row = delist_shares_row::DelistSharesRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::Faucet(instruction) => {
                let row = faucet_row::FaucetRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::Initialize(instruction) => {
                let row = initialize_row::InitializeRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::ListShares(instruction) => {
                let row = list_shares_row::ListSharesRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::RecordSale(instruction) => {
                let row = record_sale_row::RecordSaleRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RealxhubInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RealxhubInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            RealxhubInstruction::BuyShares(instruction) => {
                let row = buy_shares_row::BuySharesRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::ClaimIncome(instruction) => {
                let row = claim_income_row::ClaimIncomeRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::CreateHub(instruction) => {
                let row = create_hub_row::CreateHubRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::DelistShares(instruction) => {
                let row = delist_shares_row::DelistSharesRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::Faucet(instruction) => {
                let row = faucet_row::FaucetRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::Initialize(instruction) => {
                let row = initialize_row::InitializeRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::ListShares(instruction) => {
                let row = list_shares_row::ListSharesRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::RecordSale(instruction) => {
                let row = record_sale_row::RecordSaleRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RealxhubInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
