//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Config {
    /// Authority allowed to update parameters.
    pub authority: Pubkey,
    /// Proposed replacement authority; takes over via `accept_authority`.
    /// Two-step so a typo'd address can't brick parameter management.
    pub pending_authority: Option<Pubkey>,
    /// The XCAV mint listing and lawyer deposits are paid in.
    pub xcav_mint: Pubkey,
    /// Owner of the shared protocol treasury (a multisig on mainnet). Fees are
    /// paid to this key's token accounts; the program never holds them.
    pub treasury: Pubkey,
    /// The sponsor wallet that fronts account rent for investors. Every
    /// position close sends its lamports here, not to the investor.
    pub rent_collector: Pubkey,
    /// Mints a property can be priced and paid in. Every entry must be a
    /// same-value GBP stablecoin: prices convert between them by decimal
    /// count alone, so adding a mint of different value would misprice every
    /// open listing.
    pub accepted_payment_mints: Vec<Pubkey>,
    /// XCAV a developer locks to list a property.
    pub listing_deposit: u64,
    /// XCAV a lawyer locks to join the registry.
    pub lawyer_deposit: u64,
    /// Fewest shares a property may be split into.
    pub min_property_shares: u32,
    /// Most shares a property may be split into.
    pub max_property_shares: u32,
    /// Protocol fee taken from the developer's proceeds, in basis points.
    pub marketplace_fee_bps: u16,
    /// Fee an investor pays on top of the share price, in basis points.
    pub investor_fee_bps: u16,
    /// Largest slice of a property one investor may hold, in basis points.
    pub max_ownership_bps: u16,
    /// Seconds the claim window stays open once the SPV exists.
    pub claiming_time: i64,
    /// Seconds the legal process may run before it expires.
    pub legal_process_time: i64,
    /// Seconds the SPV lawyer election stays open once the first lawyer claims.
    pub lawyer_voting_time: i64,
    /// Share of a property's supply that must vote for the SPV lawyer election
    /// to be valid, in basis points.
    pub min_voting_quorum_bps: u16,
    /// Monotonic id for the next listing.
    pub next_listing_id: u64,
    pub bump: u8,
}

impl Config {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[155, 12, 170, 224, 30, 250, 204, 130] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
