//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct ShareListing {
    pub id: u64,
    pub asset_id: u64,
    pub seller: Pubkey,
    /// Asking price per share, in quote units.
    pub share_price: u64,
    /// Shares still for sale; partial buys draw it down.
    pub amount: u32,
    /// Marketplace fee at the moment of listing, so a config change can't
    /// reprice the seller's proceeds under them.
    pub fee_bps: u16,
    /// Stamped on each offer against this listing; the seller accepts by
    /// nonce, so an offer can't be swapped under their signature.
    pub next_offer_nonce: u64,
    /// The wallet that fronted the account's rent; refunded at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl ShareListing {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[38, 219, 182, 80, 137, 29, 254, 143] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
