//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CancelledFeesSettled")]
pub struct CancelledFeesSettledGraphQL {
    pub listing_id: U64,
    pub payment_mint: Pubkey,
    pub lawyer_paid: U64,
    pub treasury_paid: U64,
}

impl From<crate::types::CancelledFeesSettled> for CancelledFeesSettledGraphQL {
    fn from(original: crate::types::CancelledFeesSettled) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            payment_mint: carbon_core::graphql::primitives::Pubkey(original.payment_mint),
            lawyer_paid: carbon_core::graphql::primitives::U64(original.lawyer_paid),
            treasury_paid: carbon_core::graphql::primitives::U64(original.treasury_paid),
        }
    }
}
