//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CandidacyClosed")]
pub struct CandidacyClosedGraphQL {
    pub listing_id: U64,
    pub round: U64,
    pub lawyer: Pubkey,
}

impl From<crate::types::CandidacyClosed> for CandidacyClosedGraphQL {
    fn from(original: crate::types::CandidacyClosed) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            round: carbon_core::graphql::primitives::U64(original.round),
            lawyer: carbon_core::graphql::primitives::Pubkey(original.lawyer),
        }
    }
}
