//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DealExecuted")]
pub struct DealExecutedGraphQL {
    pub listing_id: U64,
    pub developer: Pubkey,
}

impl From<crate::types::DealExecuted> for DealExecutedGraphQL {
    fn from(original: crate::types::DealExecuted) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            developer: carbon_core::graphql::primitives::Pubkey(original.developer),
        }
    }
}
