//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DealPayout")]
pub struct DealPayoutGraphQL {
    pub listing_id: U64,
    pub payment_mint: Pubkey,
    pub developer: U64,
    pub developer_lawyer: U64,
    pub spv_lawyer: U64,
    pub region_owner: U64,
    pub treasury: U64,
}

impl From<crate::types::DealPayout> for DealPayoutGraphQL {
    fn from(original: crate::types::DealPayout) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            payment_mint: carbon_core::graphql::primitives::Pubkey(original.payment_mint),
            developer: carbon_core::graphql::primitives::U64(original.developer),
            developer_lawyer: carbon_core::graphql::primitives::U64(original.developer_lawyer),
            spv_lawyer: carbon_core::graphql::primitives::U64(original.spv_lawyer),
            region_owner: carbon_core::graphql::primitives::U64(original.region_owner),
            treasury: carbon_core::graphql::primitives::U64(original.treasury),
        }
    }
}
