//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DeveloperLawyerAssigned")]
pub struct DeveloperLawyerAssignedGraphQL {
    pub listing_id: U64,
    pub lawyer: Pubkey,
}

impl From<crate::types::DeveloperLawyerAssigned> for DeveloperLawyerAssignedGraphQL {
    fn from(original: crate::types::DeveloperLawyerAssigned) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            lawyer: carbon_core::graphql::primitives::Pubkey(original.lawyer),
        }
    }
}
