//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// Where a lawyer's document review stands.
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "DocumentStatus")]
pub enum DocumentStatusGraphQL {
        Pending,
        Approved,
        Rejected,
}

impl From<crate::types::DocumentStatus> for DocumentStatusGraphQL {
    fn from(original: crate::types::DocumentStatus) -> Self {
        match original {
            crate::types::DocumentStatus::Pending => Self::Pending,
            crate::types::DocumentStatus::Approved => Self::Approved,
            crate::types::DocumentStatus::Rejected => Self::Rejected,
        }
    }
}

