//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::ListingStatusGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DocumentsConfirmed")]
pub struct DocumentsConfirmedGraphQL {
    pub listing_id: U64,
    pub lawyer: Pubkey,
    pub approve: bool,
    pub documents_hash: Vec<U8>,
    pub status: ListingStatusGraphQL,
}

impl From<crate::types::DocumentsConfirmed> for DocumentsConfirmedGraphQL {
    fn from(original: crate::types::DocumentsConfirmed) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            lawyer: carbon_core::graphql::primitives::Pubkey(original.lawyer),
            approve: original.approve,
            documents_hash: original.documents_hash.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            status: original.status.into(),
        }
    }
}
