//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LawyerRegistered")]
pub struct LawyerRegisteredGraphQL {
    pub lawyer: Pubkey,
    pub region_id: i32,
    pub deposit: U64,
}

impl From<crate::types::LawyerRegistered> for LawyerRegisteredGraphQL {
    fn from(original: crate::types::LawyerRegistered) -> Self {
        Self {
            lawyer: carbon_core::graphql::primitives::Pubkey(original.lawyer),
            region_id: original.region_id as i32,
            deposit: carbon_core::graphql::primitives::U64(original.deposit),
        }
    }
}
