//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// Where a primary listing is in its lifecycle.
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "ListingStatus")]
pub enum ListingStatusGraphQL {
        PendingAssets,
        Listed,
        SoldOut,
        Legal,
        Finalized,
        Expired,
        Cancelled,
        Refunding,
}

impl From<crate::types::ListingStatus> for ListingStatusGraphQL {
    fn from(original: crate::types::ListingStatus) -> Self {
        match original {
            crate::types::ListingStatus::PendingAssets => Self::PendingAssets,
            crate::types::ListingStatus::Listed => Self::Listed,
            crate::types::ListingStatus::SoldOut => Self::SoldOut,
            crate::types::ListingStatus::Legal => Self::Legal,
            crate::types::ListingStatus::Finalized => Self::Finalized,
            crate::types::ListingStatus::Expired => Self::Expired,
            crate::types::ListingStatus::Cancelled => Self::Cancelled,
            crate::types::ListingStatus::Refunding => Self::Refunding,
        }
    }
}

