//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "OfferCancelled")]
pub struct OfferCancelledGraphQL {
    pub listing_id: U64,
    pub offeror: Pubkey,
    pub refunded: U64,
}

impl From<crate::types::OfferCancelled> for OfferCancelledGraphQL {
    fn from(original: crate::types::OfferCancelled) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            offeror: carbon_core::graphql::primitives::Pubkey(original.offeror),
            refunded: carbon_core::graphql::primitives::U64(original.refunded),
        }
    }
}
