//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PropertyAssetsInitialized")]
pub struct PropertyAssetsInitializedGraphQL {
    pub listing_id: U64,
    pub share_mint: Pubkey,
    pub share_amount: U32,
}

impl From<crate::types::PropertyAssetsInitialized> for PropertyAssetsInitializedGraphQL {
    fn from(original: crate::types::PropertyAssetsInitialized) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            share_mint: carbon_core::graphql::primitives::Pubkey(original.share_mint),
            share_amount: carbon_core::graphql::primitives::U32(original.share_amount),
        }
    }
}
