//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RelistedSharesBought")]
pub struct RelistedSharesBoughtGraphQL {
    pub id: U64,
    pub asset_id: U64,
    pub buyer: Pubkey,
    pub seller: Pubkey,
    pub amount: U32,
    pub mint: Pubkey,
    pub paid: U64,
    pub fee: U64,
    pub remaining: U32,
}

impl From<crate::types::RelistedSharesBought> for RelistedSharesBoughtGraphQL {
    fn from(original: crate::types::RelistedSharesBought) -> Self {
        Self {
            id: carbon_core::graphql::primitives::U64(original.id),
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            buyer: carbon_core::graphql::primitives::Pubkey(original.buyer),
            seller: carbon_core::graphql::primitives::Pubkey(original.seller),
            amount: carbon_core::graphql::primitives::U32(original.amount),
            mint: carbon_core::graphql::primitives::Pubkey(original.mint),
            paid: carbon_core::graphql::primitives::U64(original.paid),
            fee: carbon_core::graphql::primitives::U64(original.fee),
            remaining: carbon_core::graphql::primitives::U32(original.remaining),
        }
    }
}
