//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ReservationReleased")]
pub struct ReservationReleasedGraphQL {
    pub listing_id: U64,
    pub investor: Pubkey,
    pub amount: U32,
}

impl From<crate::types::ReservationReleased> for ReservationReleasedGraphQL {
    fn from(original: crate::types::ReservationReleased) -> Self {
        Self {
            listing_id: carbon_core::graphql::primitives::U64(original.listing_id),
            investor: carbon_core::graphql::primitives::Pubkey(original.investor),
            amount: carbon_core::graphql::primitives::U32(original.amount),
        }
    }
}
