//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ShareHoldingClosed")]
pub struct ShareHoldingClosedGraphQL {
    pub asset_id: U64,
    pub owner: Pubkey,
}

impl From<crate::types::ShareHoldingClosed> for ShareHoldingClosedGraphQL {
    fn from(original: crate::types::ShareHoldingClosed) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            owner: carbon_core::graphql::primitives::Pubkey(original.owner),
        }
    }
}
