//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AssignDeveloperLawyer {
    pub listing_id: u64,
    pub lawyer: Pubkey,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AssignDeveloperLawyerInstructionAccounts {
    pub developer: solana_pubkey::Pubkey,
    pub developer_role: solana_pubkey::Pubkey,
    pub lawyer_role: solana_pubkey::Pubkey,
    pub registry: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AssignDeveloperLawyer {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[197, 167, 242, 89, 235, 9, 169, 65] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for AssignDeveloperLawyer {
    type ArrangedAccounts = AssignDeveloperLawyerInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let developer = next_account(&mut iter)?;
        let developer_role = next_account(&mut iter)?;
        let lawyer_role = next_account(&mut iter)?;
        let registry = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AssignDeveloperLawyerInstructionAccounts {
            developer,
            developer_role,
            lawyer_role,
            registry,
            listing,
            property,
            remaining: remaining.to_vec(),
        })
    }
}
