//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct BuyRelistedShares {
    pub asset_id: u64,
    pub id: u64,
    pub amount: u32,
    pub max_total_cost: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyRelistedSharesInstructionAccounts {
    pub buyer: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub buyer_role: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub share_listing: solana_pubkey::Pubkey,
    pub seller: solana_pubkey::Pubkey,
    pub rent_payer: solana_pubkey::Pubkey,
    pub seller_holding: solana_pubkey::Pubkey,
    pub buyer_holding: solana_pubkey::Pubkey,
    pub payment_mint: solana_pubkey::Pubkey,
    pub buyer_payment: solana_pubkey::Pubkey,
    pub seller_payment: solana_pubkey::Pubkey,
    pub treasury: solana_pubkey::Pubkey,
    pub treasury_payment: solana_pubkey::Pubkey,
    pub share_mint: solana_pubkey::Pubkey,
    pub mint_auth: solana_pubkey::Pubkey,
    pub seller_share_account: solana_pubkey::Pubkey,
    pub buyer_share_account: solana_pubkey::Pubkey,
    pub cpi_auth: solana_pubkey::Pubkey,
    pub income: solana_pubkey::Pubkey,
    pub seller_checkpoint: solana_pubkey::Pubkey,
    pub buyer_checkpoint: solana_pubkey::Pubkey,
    pub property_program: solana_pubkey::Pubkey,
    pub payment_token_program: solana_pubkey::Pubkey,
    pub share_token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl BuyRelistedShares {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[205, 204, 84, 12, 55, 204, 167, 234] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for BuyRelistedShares {
    type ArrangedAccounts = BuyRelistedSharesInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let buyer = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let buyer_role = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let share_listing = next_account(&mut iter)?;
        let seller = next_account(&mut iter)?;
        let rent_payer = next_account(&mut iter)?;
        let seller_holding = next_account(&mut iter)?;
        let buyer_holding = next_account(&mut iter)?;
        let payment_mint = next_account(&mut iter)?;
        let buyer_payment = next_account(&mut iter)?;
        let seller_payment = next_account(&mut iter)?;
        let treasury = next_account(&mut iter)?;
        let treasury_payment = next_account(&mut iter)?;
        let share_mint = next_account(&mut iter)?;
        let mint_auth = next_account(&mut iter)?;
        let seller_share_account = next_account(&mut iter)?;
        let buyer_share_account = next_account(&mut iter)?;
        let cpi_auth = next_account(&mut iter)?;
        let income = next_account(&mut iter)?;
        let seller_checkpoint = next_account(&mut iter)?;
        let buyer_checkpoint = next_account(&mut iter)?;
        let property_program = next_account(&mut iter)?;
        let payment_token_program = next_account(&mut iter)?;
        let share_token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(BuyRelistedSharesInstructionAccounts {
            buyer,
            payer,
            buyer_role,
            config,
            listing,
            property,
            share_listing,
            seller,
            rent_payer,
            seller_holding,
            buyer_holding,
            payment_mint,
            buyer_payment,
            seller_payment,
            treasury,
            treasury_payment,
            share_mint,
            mint_auth,
            seller_share_account,
            buyer_share_account,
            cpi_auth,
            income,
            seller_checkpoint,
            buyer_checkpoint,
            property_program,
            payment_token_program,
            share_token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
