//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CancelOffer {
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CancelOfferInstructionAccounts {
    pub offeror: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub offer: solana_pubkey::Pubkey,
    pub offer_rent_payer: solana_pubkey::Pubkey,
    pub payment_mint: solana_pubkey::Pubkey,
    pub offer_vault: solana_pubkey::Pubkey,
    pub vault_payment_account: solana_pubkey::Pubkey,
    pub offeror_payment: solana_pubkey::Pubkey,
    pub payment_token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CancelOffer {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[92, 203, 223, 40, 92, 89, 53, 119] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CancelOffer {
    type ArrangedAccounts = CancelOfferInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let offeror = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let offer = next_account(&mut iter)?;
        let offer_rent_payer = next_account(&mut iter)?;
        let payment_mint = next_account(&mut iter)?;
        let offer_vault = next_account(&mut iter)?;
        let vault_payment_account = next_account(&mut iter)?;
        let offeror_payment = next_account(&mut iter)?;
        let payment_token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CancelOfferInstructionAccounts {
            offeror,
            payer,
            offer,
            offer_rent_payer,
            payment_mint,
            offer_vault,
            vault_payment_account,
            offeror_payment,
            payment_token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
