//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CloseShareHolding {
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CloseShareHoldingInstructionAccounts {
    pub cranker: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub rent_collector: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub holding: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CloseShareHolding {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[184, 83, 50, 153, 169, 129, 37, 176] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CloseShareHolding {
    type ArrangedAccounts = CloseShareHoldingInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let cranker = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let rent_collector = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let holding = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CloseShareHoldingInstructionAccounts {
            cranker,
            config,
            rent_collector,
            property,
            holding,
            remaining: remaining.to_vec(),
        })
    }
}
