//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CloseCandidacy {
    pub listing_id: u64,
    pub round: u64,
    pub lawyer: Pubkey,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CloseCandidacyInstructionAccounts {
    pub cranker: solana_pubkey::Pubkey,
    pub rent_payer: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub candidacy: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CloseCandidacy {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[219, 28, 41, 13, 28, 103, 134, 84] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CloseCandidacy {
    type ArrangedAccounts = CloseCandidacyInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let cranker = next_account(&mut iter)?;
        let rent_payer = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let candidacy = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CloseCandidacyInstructionAccounts {
            cranker,
            rent_payer,
            listing,
            candidacy,
            remaining: remaining.to_vec(),
        })
    }
}
