//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CloseReservation {
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CloseReservationInstructionAccounts {
    pub cranker: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub rent_collector: solana_pubkey::Pubkey,
    pub reservation: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CloseReservation {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[171, 96, 8, 85, 100, 252, 173, 204] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CloseReservation {
    type ArrangedAccounts = CloseReservationInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let cranker = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let rent_collector = next_account(&mut iter)?;
        let reservation = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CloseReservationInstructionAccounts {
            cranker,
            config,
            rent_collector,
            reservation,
            remaining: remaining.to_vec(),
        })
    }
}
