//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CloseCancelledPosition {
    pub listing_id: u64,
    pub investor: Pubkey,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CloseCancelledPositionInstructionAccounts {
    pub cranker: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub rent_collector: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub position: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CloseCancelledPosition {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[165, 241, 53, 73, 152, 29, 198, 117] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CloseCancelledPosition {
    type ArrangedAccounts = CloseCancelledPositionInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let cranker = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let rent_collector = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let position = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CloseCancelledPositionInstructionAccounts {
            cranker,
            config,
            rent_collector,
            listing,
            position,
            remaining: remaining.to_vec(),
        })
    }
}
