//! This code was AUTOGENERATED using the Codama library.

use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
pub use super::super::events;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, carbon_core::borsh::BorshSerialize, carbon_core::borsh::BorshDeserialize, PartialEq)]
pub enum CpiEvent {
    AuthorityUpdateProposed(events::authority_update_proposed::AuthorityUpdateProposedEvent),
    AuthorityUpdated(events::authority_updated::AuthorityUpdatedEvent),
    CancelledFeesSettled(events::cancelled_fees_settled::CancelledFeesSettledEvent),
    CancelledPositionClosed(events::cancelled_position_closed::CancelledPositionClosedEvent),
    CancelledSharesWithdrawn(events::cancelled_shares_withdrawn::CancelledSharesWithdrawnEvent),
    CandidacyClosed(events::candidacy_closed::CandidacyClosedEvent),
    CaseClosed(events::case_closed::CaseClosedEvent),
    ConfigInitialized(events::config_initialized::ConfigInitializedEvent),
    ConfigUpdated(events::config_updated::ConfigUpdatedEvent),
    DeadListingClosed(events::dead_listing_closed::DeadListingClosedEvent),
    DealExecuted(events::deal_executed::DealExecutedEvent),
    DealPayout(events::deal_payout::DealPayoutEvent),
    DeveloperLawyerAssigned(events::developer_lawyer_assigned::DeveloperLawyerAssignedEvent),
    DocumentsConfirmed(events::documents_confirmed::DocumentsConfirmedEvent),
    ExpiredSharesWithdrawn(events::expired_shares_withdrawn::ExpiredSharesWithdrawnEvent),
    LawyerRegistered(events::lawyer_registered::LawyerRegisteredEvent),
    LawyerResigned(events::lawyer_resigned::LawyerResignedEvent),
    LawyerUnregistered(events::lawyer_unregistered::LawyerUnregisteredEvent),
    LegalTimeoutSharesWithdrawn(events::legal_timeout_shares_withdrawn::LegalTimeoutSharesWithdrawnEvent),
    ListingDepositWithdrawn(events::listing_deposit_withdrawn::ListingDepositWithdrawnEvent),
    ObjectUpdated(events::object_updated::ObjectUpdatedEvent),
    PropertyAssetsInitialized(events::property_assets_initialized::PropertyAssetsInitializedEvent),
    PropertyListed(events::property_listed::PropertyListedEvent),
    PropertySharesBought(events::property_shares_bought::PropertySharesBoughtEvent),
    ReservationReleased(events::reservation_released::ReservationReleasedEvent),
    SharesClaimed(events::shares_claimed::SharesClaimedEvent),
    SharesReserved(events::shares_reserved::SharesReservedEvent),
    SharesUnreserved(events::shares_unreserved::SharesUnreservedEvent),
    SilentVerdictResolved(events::silent_verdict_resolved::SilentVerdictResolvedEvent),
    SpvCaseClaimed(events::spv_case_claimed::SpvCaseClaimedEvent),
    SpvCreated(events::spv_created::SpvCreatedEvent),
    SpvElectionFinalized(events::spv_election_finalized::SpvElectionFinalizedEvent),
    SpvLawyerVoteCast(events::spv_lawyer_vote_cast::SpvLawyerVoteCastEvent),
    VotingSharesUnlocked(events::voting_shares_unlocked::VotingSharesUnlockedEvent),
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CpiEventInstructionAccounts {
    pub program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CpiEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[228, 69, 165, 46, 81, 203, 154, 29] {
            return None;
        }

        let event_data = &data[8..];

                if let Some(decoded) = events::authority_update_proposed::AuthorityUpdateProposedEvent::decode(event_data) {
            return Some(CpiEvent::AuthorityUpdateProposed(decoded));
        }
                if let Some(decoded) = events::authority_updated::AuthorityUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::AuthorityUpdated(decoded));
        }
                if let Some(decoded) = events::cancelled_fees_settled::CancelledFeesSettledEvent::decode(event_data) {
            return Some(CpiEvent::CancelledFeesSettled(decoded));
        }
                if let Some(decoded) = events::cancelled_position_closed::CancelledPositionClosedEvent::decode(event_data) {
            return Some(CpiEvent::CancelledPositionClosed(decoded));
        }
                if let Some(decoded) = events::cancelled_shares_withdrawn::CancelledSharesWithdrawnEvent::decode(event_data) {
            return Some(CpiEvent::CancelledSharesWithdrawn(decoded));
        }
                if let Some(decoded) = events::candidacy_closed::CandidacyClosedEvent::decode(event_data) {
            return Some(CpiEvent::CandidacyClosed(decoded));
        }
                if let Some(decoded) = events::case_closed::CaseClosedEvent::decode(event_data) {
            return Some(CpiEvent::CaseClosed(decoded));
        }
                if let Some(decoded) = events::config_initialized::ConfigInitializedEvent::decode(event_data) {
            return Some(CpiEvent::ConfigInitialized(decoded));
        }
                if let Some(decoded) = events::config_updated::ConfigUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::ConfigUpdated(decoded));
        }
                if let Some(decoded) = events::dead_listing_closed::DeadListingClosedEvent::decode(event_data) {
            return Some(CpiEvent::DeadListingClosed(decoded));
        }
                if let Some(decoded) = events::deal_executed::DealExecutedEvent::decode(event_data) {
            return Some(CpiEvent::DealExecuted(decoded));
        }
                if let Some(decoded) = events::deal_payout::DealPayoutEvent::decode(event_data) {
            return Some(CpiEvent::DealPayout(decoded));
        }
                if let Some(decoded) = events::developer_lawyer_assigned::DeveloperLawyerAssignedEvent::decode(event_data) {
            return Some(CpiEvent::DeveloperLawyerAssigned(decoded));
        }
                if let Some(decoded) = events::documents_confirmed::DocumentsConfirmedEvent::decode(event_data) {
            return Some(CpiEvent::DocumentsConfirmed(decoded));
        }
                if let Some(decoded) = events::expired_shares_withdrawn::ExpiredSharesWithdrawnEvent::decode(event_data) {
            return Some(CpiEvent::ExpiredSharesWithdrawn(decoded));
        }
                if let Some(decoded) = events::lawyer_registered::LawyerRegisteredEvent::decode(event_data) {
            return Some(CpiEvent::LawyerRegistered(decoded));
        }
                if let Some(decoded) = events::lawyer_resigned::LawyerResignedEvent::decode(event_data) {
            return Some(CpiEvent::LawyerResigned(decoded));
        }
                if let Some(decoded) = events::lawyer_unregistered::LawyerUnregisteredEvent::decode(event_data) {
            return Some(CpiEvent::LawyerUnregistered(decoded));
        }
                if let Some(decoded) = events::legal_timeout_shares_withdrawn::LegalTimeoutSharesWithdrawnEvent::decode(event_data) {
            return Some(CpiEvent::LegalTimeoutSharesWithdrawn(decoded));
        }
                if let Some(decoded) = events::listing_deposit_withdrawn::ListingDepositWithdrawnEvent::decode(event_data) {
            return Some(CpiEvent::ListingDepositWithdrawn(decoded));
        }
                if let Some(decoded) = events::object_updated::ObjectUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::ObjectUpdated(decoded));
        }
                if let Some(decoded) = events::property_assets_initialized::PropertyAssetsInitializedEvent::decode(event_data) {
            return Some(CpiEvent::PropertyAssetsInitialized(decoded));
        }
                if let Some(decoded) = events::property_listed::PropertyListedEvent::decode(event_data) {
            return Some(CpiEvent::PropertyListed(decoded));
        }
                if let Some(decoded) = events::property_shares_bought::PropertySharesBoughtEvent::decode(event_data) {
            return Some(CpiEvent::PropertySharesBought(decoded));
        }
                if let Some(decoded) = events::reservation_released::ReservationReleasedEvent::decode(event_data) {
            return Some(CpiEvent::ReservationReleased(decoded));
        }
                if let Some(decoded) = events::shares_claimed::SharesClaimedEvent::decode(event_data) {
            return Some(CpiEvent::SharesClaimed(decoded));
        }
                if let Some(decoded) = events::shares_reserved::SharesReservedEvent::decode(event_data) {
            return Some(CpiEvent::SharesReserved(decoded));
        }
                if let Some(decoded) = events::shares_unreserved::SharesUnreservedEvent::decode(event_data) {
            return Some(CpiEvent::SharesUnreserved(decoded));
        }
                if let Some(decoded) = events::silent_verdict_resolved::SilentVerdictResolvedEvent::decode(event_data) {
            return Some(CpiEvent::SilentVerdictResolved(decoded));
        }
                if let Some(decoded) = events::spv_case_claimed::SpvCaseClaimedEvent::decode(event_data) {
            return Some(CpiEvent::SpvCaseClaimed(decoded));
        }
                if let Some(decoded) = events::spv_created::SpvCreatedEvent::decode(event_data) {
            return Some(CpiEvent::SpvCreated(decoded));
        }
                if let Some(decoded) = events::spv_election_finalized::SpvElectionFinalizedEvent::decode(event_data) {
            return Some(CpiEvent::SpvElectionFinalized(decoded));
        }
                if let Some(decoded) = events::spv_lawyer_vote_cast::SpvLawyerVoteCastEvent::decode(event_data) {
            return Some(CpiEvent::SpvLawyerVoteCast(decoded));
        }
                if let Some(decoded) = events::voting_shares_unlocked::VotingSharesUnlockedEvent::decode(event_data) {
            return Some(CpiEvent::VotingSharesUnlocked(decoded));
        }
                None
    }
}

impl ArrangeAccounts for CpiEvent {
    type ArrangedAccounts = CpiEventInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let [program, event_authority, remaining @ ..] = accounts else {
            return None;
        };

        Some(CpiEventInstructionAccounts {
            program: program.pubkey,
            event_authority: event_authority.pubkey,
            remaining: remaining.to_vec(),
        })
    }
}

