//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct InitPropertyAssets {
    pub listing_id: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitPropertyAssetsInstructionAccounts {
    pub developer: solana_pubkey::Pubkey,
    pub developer_role: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub share_mint: solana_pubkey::Pubkey,
    pub mint_auth: solana_pubkey::Pubkey,
    pub property_vault: solana_pubkey::Pubkey,
    pub vault_share_account: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl InitPropertyAssets {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[86, 217, 248, 184, 33, 187, 144, 253] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for InitPropertyAssets {
    type ArrangedAccounts = InitPropertyAssetsInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let developer = next_account(&mut iter)?;
        let developer_role = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let share_mint = next_account(&mut iter)?;
        let mint_auth = next_account(&mut iter)?;
        let property_vault = next_account(&mut iter)?;
        let vault_share_account = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitPropertyAssetsInstructionAccounts {
            developer,
            developer_role,
            listing,
            property,
            share_mint,
            mint_auth,
            property_vault,
            vault_share_account,
            token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
