//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct ResignFromCase {
    pub listing_id: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ResignFromCaseInstructionAccounts {
    pub lawyer: solana_pubkey::Pubkey,
    pub registry: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ResignFromCase {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[158, 242, 127, 206, 24, 126, 203, 66] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ResignFromCase {
    type ArrangedAccounts = ResignFromCaseInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let lawyer = next_account(&mut iter)?;
        let registry = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ResignFromCaseInstructionAccounts {
            lawyer,
            registry,
            listing,
            remaining: remaining.to_vec(),
        })
    }
}
