//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct SendPropertyShares {
    pub asset_id: u64,
    pub amount: u32,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SendPropertySharesInstructionAccounts {
    pub sender: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub sender_role: solana_pubkey::Pubkey,
    pub receiver: solana_pubkey::Pubkey,
    pub receiver_role: solana_pubkey::Pubkey,
    pub listing: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub sender_holding: solana_pubkey::Pubkey,
    pub receiver_holding: solana_pubkey::Pubkey,
    pub share_mint: solana_pubkey::Pubkey,
    pub mint_auth: solana_pubkey::Pubkey,
    pub sender_share_account: solana_pubkey::Pubkey,
    pub receiver_share_account: solana_pubkey::Pubkey,
    pub cpi_auth: solana_pubkey::Pubkey,
    pub income: solana_pubkey::Pubkey,
    pub sender_checkpoint: solana_pubkey::Pubkey,
    pub receiver_checkpoint: solana_pubkey::Pubkey,
    pub property_program: solana_pubkey::Pubkey,
    pub share_token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl SendPropertyShares {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[214, 10, 132, 137, 120, 190, 89, 240] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for SendPropertyShares {
    type ArrangedAccounts = SendPropertySharesInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let sender = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let sender_role = next_account(&mut iter)?;
        let receiver = next_account(&mut iter)?;
        let receiver_role = next_account(&mut iter)?;
        let listing = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let sender_holding = next_account(&mut iter)?;
        let receiver_holding = next_account(&mut iter)?;
        let share_mint = next_account(&mut iter)?;
        let mint_auth = next_account(&mut iter)?;
        let sender_share_account = next_account(&mut iter)?;
        let receiver_share_account = next_account(&mut iter)?;
        let cpi_auth = next_account(&mut iter)?;
        let income = next_account(&mut iter)?;
        let sender_checkpoint = next_account(&mut iter)?;
        let receiver_checkpoint = next_account(&mut iter)?;
        let property_program = next_account(&mut iter)?;
        let share_token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(SendPropertySharesInstructionAccounts {
            sender,
            payer,
            sender_role,
            receiver,
            receiver_role,
            listing,
            property,
            sender_holding,
            receiver_holding,
            share_mint,
            mint_auth,
            sender_share_account,
            receiver_share_account,
            cpi_auth,
            income,
            sender_checkpoint,
            receiver_checkpoint,
            property_program,
            share_token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
