//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateAuthority")]
pub struct UpdateAuthorityGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub new_authority: Pubkey,
}

impl TryFrom<crate::instructions::postgres::UpdateAuthorityRow> for UpdateAuthorityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::UpdateAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            new_authority: carbon_core::graphql::primitives::Pubkey(row.new_authority.0),
        })
    }
}
