//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct RegionsDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("5iupkzVtWxee48UXh3s615V9sXXuYjsSr61VPuduXdPc");

pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
