//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentVotesUnlocked")]
pub struct AgentVotesUnlockedGraphQL {
    pub asset_id: U64,
    pub round: U64,
    pub voter: Pubkey,
    pub power: U32,
}

impl From<crate::types::AgentVotesUnlocked> for AgentVotesUnlockedGraphQL {
    fn from(original: crate::types::AgentVotesUnlocked) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            round: carbon_core::graphql::primitives::U64(original.round),
            voter: carbon_core::graphql::primitives::Pubkey(original.voter),
            power: carbon_core::graphql::primitives::U32(original.power),
        }
    }
}
