//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentResignationFinalized")]
pub struct AgentResignationFinalizedGraphQL {
    pub asset_id: U64,
    pub agent: Pubkey,
}

impl From<crate::types::AgentResignationFinalized> for AgentResignationFinalizedGraphQL {
    fn from(original: crate::types::AgentResignationFinalized) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            agent: carbon_core::graphql::primitives::Pubkey(original.agent),
        }
    }
}
