//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentVoteCast")]
pub struct AgentVoteCastGraphQL {
    pub asset_id: U64,
    pub round: U64,
    pub voter: Pubkey,
    pub choice: Pubkey,
    pub power: U32,
}

impl From<crate::types::AgentVoteCast> for AgentVoteCastGraphQL {
    fn from(original: crate::types::AgentVoteCast) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            round: carbon_core::graphql::primitives::U64(original.round),
            voter: carbon_core::graphql::primitives::Pubkey(original.voter),
            choice: carbon_core::graphql::primitives::Pubkey(original.choice),
            power: carbon_core::graphql::primitives::U32(original.power),
        }
    }
}
