//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AgentCandidacyClosed")]
pub struct AgentCandidacyClosedGraphQL {
    pub asset_id: U64,
    pub round: U64,
    pub agent: Pubkey,
}

impl From<crate::types::AgentCandidacyClosed> for AgentCandidacyClosedGraphQL {
    fn from(original: crate::types::AgentCandidacyClosed) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            round: carbon_core::graphql::primitives::U64(original.round),
            agent: carbon_core::graphql::primitives::Pubkey(original.agent),
        }
    }
}
