//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ChallengeOpened")]
pub struct ChallengeOpenedGraphQL {
    pub asset_id: U64,
    pub id: U64,
    pub challenger: Pubkey,
    pub agent: Pubkey,
    pub deposit: U64,
    pub expiry: I64,
}

impl From<crate::types::ChallengeOpened> for ChallengeOpenedGraphQL {
    fn from(original: crate::types::ChallengeOpened) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            id: carbon_core::graphql::primitives::U64(original.id),
            challenger: carbon_core::graphql::primitives::Pubkey(original.challenger),
            agent: carbon_core::graphql::primitives::Pubkey(original.agent),
            deposit: carbon_core::graphql::primitives::U64(original.deposit),
            expiry: carbon_core::graphql::primitives::I64(original.expiry),
        }
    }
}
