//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "GovState")]
pub struct GovStateGraphQL {
    pub proposal_count: U64,
    pub challenge_count: U64,
    pub active_proposal: U64,
    pub active_challenge: U64,
    pub strikes: U8,
    pub last_auto_approval_ts: I64,
}

impl From<crate::types::GovState> for GovStateGraphQL {
    fn from(original: crate::types::GovState) -> Self {
        Self {
            proposal_count: carbon_core::graphql::primitives::U64(original.proposal_count),
            challenge_count: carbon_core::graphql::primitives::U64(original.challenge_count),
            active_proposal: carbon_core::graphql::primitives::U64(original.active_proposal),
            active_challenge: carbon_core::graphql::primitives::U64(original.active_challenge),
            strikes: carbon_core::graphql::primitives::U8(original.strikes),
            last_auto_approval_ts: carbon_core::graphql::primitives::I64(original.last_auto_approval_ts),
        }
    }
}
