//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LettingAgentRemoved")]
pub struct LettingAgentRemovedGraphQL {
    pub agent: Pubkey,
    pub postcode: Vec<U8>,
    pub deposit: U64,
}

impl From<crate::types::LettingAgentRemoved> for LettingAgentRemovedGraphQL {
    fn from(original: crate::types::LettingAgentRemoved) -> Self {
        Self {
            agent: carbon_core::graphql::primitives::Pubkey(original.agent),
            postcode: original.postcode.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            deposit: carbon_core::graphql::primitives::U64(original.deposit),
        }
    }
}
