//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ProposalExecuted")]
pub struct ProposalExecutedGraphQL {
    pub asset_id: U64,
    pub amount: U64,
}

impl From<crate::types::ProposalExecuted> for ProposalExecutedGraphQL {
    fn from(original: crate::types::ProposalExecuted) -> Self {
        Self {
            asset_id: carbon_core::graphql::primitives::U64(original.asset_id),
            amount: carbon_core::graphql::primitives::U64(original.amount),
        }
    }
}
