//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::AccessPermissionGraphQL;
use crate::types::graphql::RoleGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RoleAccount")]
pub struct RoleAccountGraphQL {
    pub user: Pubkey,
    pub role: RoleGraphQL,
    pub permission: AccessPermissionGraphQL,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl From<crate::types::RoleAccount> for RoleAccountGraphQL {
    fn from(original: crate::types::RoleAccount) -> Self {
        Self {
            user: carbon_core::graphql::primitives::Pubkey(original.user),
            role: original.role.into(),
            permission: original.permission.into(),
            rent_payer: carbon_core::graphql::primitives::Pubkey(original.rent_payer),
            bump: carbon_core::graphql::primitives::U8(original.bump),
        }
    }
}
