//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// A vote's direction. Abstain counts toward quorum but neither side.
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "VoteChoice")]
pub enum VoteChoiceGraphQL {
        Yes,
        No,
        Abstain,
}

impl From<crate::types::VoteChoice> for VoteChoiceGraphQL {
    fn from(original: crate::types::VoteChoice) -> Self {
        match original {
            crate::types::VoteChoice::Yes => Self::Yes,
            crate::types::VoteChoice::No => Self::No,
            crate::types::VoteChoice::Abstain => Self::Abstain,
        }
    }
}

