//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct PropertyDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("deCp9srk9C6P4BXJaFpjR5H6Jsm6DCq8AL2kk338dVq");

pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
