//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AcceptOfferRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub id: U64,
    pub nonce: U64,
}

impl AcceptOfferRow {
    pub fn from_parts(source: crate::instructions::accept_offer::AcceptOffer, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            id: source.id.into(),
            nonce: source.nonce.into(),
        }
    }
}

impl TryFrom<AcceptOfferRow> for crate::instructions::accept_offer::AcceptOffer {
    type Error = carbon_core::error::Error;
    fn try_from(source: AcceptOfferRow) -> Result<Self, Self::Error> {
        Ok(Self {
            id: *source.id,
            nonce: *source.nonce,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::accept_offer::AcceptOffer {
    fn table() -> &'static str {
        "accept_offer_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "id",
            "nonce",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AcceptOfferRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO accept_offer_instruction (
                "id",
                "nonce",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            )"#)
        .bind(self.id.clone())
        .bind(self.nonce.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AcceptOfferRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO accept_offer_instruction (
                "id",
                "nonce",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "id" = EXCLUDED."id",
                "nonce" = EXCLUDED."nonce",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.id.clone())
        .bind(self.nonce.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AcceptOfferRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM accept_offer_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AcceptOfferRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM accept_offer_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AcceptOfferMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AcceptOfferMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS accept_offer_instruction (
                -- Instruction data
                "id" NUMERIC(20) NOT NULL,
                "nonce" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS accept_offer_instruction"#).execute(connection).await?;
        Ok(())
    }
}
