//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct CloseCandidacyRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub listing_id: U64,
    pub round: U64,
    pub lawyer: Pubkey,
}

impl CloseCandidacyRow {
    pub fn from_parts(source: crate::instructions::close_candidacy::CloseCandidacy, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            listing_id: source.listing_id.into(),
            round: source.round.into(),
            lawyer: source.lawyer.into(),
        }
    }
}

impl TryFrom<CloseCandidacyRow> for crate::instructions::close_candidacy::CloseCandidacy {
    type Error = carbon_core::error::Error;
    fn try_from(source: CloseCandidacyRow) -> Result<Self, Self::Error> {
        Ok(Self {
            listing_id: *source.listing_id,
            round: *source.round,
            lawyer: *source.lawyer,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::close_candidacy::CloseCandidacy {
    fn table() -> &'static str {
        "close_candidacy_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "listing_id",
            "round",
            "lawyer",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CloseCandidacyRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO close_candidacy_instruction (
                "listing_id",
                "round",
                "lawyer",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.listing_id.clone())
        .bind(self.round.clone())
        .bind(self.lawyer.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CloseCandidacyRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO close_candidacy_instruction (
                "listing_id",
                "round",
                "lawyer",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "listing_id" = EXCLUDED."listing_id",
                "round" = EXCLUDED."round",
                "lawyer" = EXCLUDED."lawyer",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.listing_id.clone())
        .bind(self.round.clone())
        .bind(self.lawyer.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for CloseCandidacyRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM close_candidacy_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for CloseCandidacyRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM close_candidacy_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct CloseCandidacyMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for CloseCandidacyMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS close_candidacy_instruction (
                -- Instruction data
                "listing_id" NUMERIC(20) NOT NULL,
                "round" NUMERIC(20) NOT NULL,
                "lawyer" BYTEA NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS close_candidacy_instruction"#).execute(connection).await?;
        Ok(())
    }
}
