//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U32;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ListPropertyRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub region_id: U16,
    pub postcode: Vec<u8>,
    pub share_price: U64,
    pub share_amount: U32,
    pub tax_paid_by_developer: bool,
    pub max_deposit: U64,
}

impl ListPropertyRow {
    pub fn from_parts(source: crate::instructions::list_property::ListProperty, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            region_id: source.region_id.into(),
            postcode: source.postcode.into(),
            share_price: source.share_price.into(),
            share_amount: source.share_amount.into(),
            tax_paid_by_developer: source.tax_paid_by_developer.into(),
            max_deposit: source.max_deposit.into(),
        }
    }
}

impl TryFrom<ListPropertyRow> for crate::instructions::list_property::ListProperty {
    type Error = carbon_core::error::Error;
    fn try_from(source: ListPropertyRow) -> Result<Self, Self::Error> {
        Ok(Self {
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            postcode: source.postcode.into(),
            share_price: *source.share_price,
            share_amount: source.share_amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            tax_paid_by_developer: source.tax_paid_by_developer.into(),
            max_deposit: *source.max_deposit,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::list_property::ListProperty {
    fn table() -> &'static str {
        "list_property_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "region_id",
            "postcode",
            "share_price",
            "share_amount",
            "tax_paid_by_developer",
            "max_deposit",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ListPropertyRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO list_property_instruction (
                "region_id",
                "postcode",
                "share_price",
                "share_amount",
                "tax_paid_by_developer",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            )"#)
        .bind(self.region_id.clone())
        .bind(self.postcode.clone())
        .bind(self.share_price.clone())
        .bind(self.share_amount.clone())
        .bind(self.tax_paid_by_developer.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ListPropertyRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO list_property_instruction (
                "region_id",
                "postcode",
                "share_price",
                "share_amount",
                "tax_paid_by_developer",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "region_id" = EXCLUDED."region_id",
                "postcode" = EXCLUDED."postcode",
                "share_price" = EXCLUDED."share_price",
                "share_amount" = EXCLUDED."share_amount",
                "tax_paid_by_developer" = EXCLUDED."tax_paid_by_developer",
                "max_deposit" = EXCLUDED."max_deposit",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.region_id.clone())
        .bind(self.postcode.clone())
        .bind(self.share_price.clone())
        .bind(self.share_amount.clone())
        .bind(self.tax_paid_by_developer.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ListPropertyRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM list_property_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ListPropertyRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM list_property_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ListPropertyMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ListPropertyMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS list_property_instruction (
                -- Instruction data
                "region_id" INT4 NOT NULL,
                "postcode" BYTEA NOT NULL,
                "share_price" NUMERIC(20) NOT NULL,
                "share_amount" INT8 NOT NULL,
                "tax_paid_by_developer" BOOLEAN NOT NULL,
                "max_deposit" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS list_property_instruction"#).execute(connection).await?;
        Ok(())
    }
}
