//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U8;
use crate::types::AgentLocation;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct LettingAgentRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub wallet: Pubkey,
    pub region_id: U16,
    pub locations: sqlx::types::Json<Vec<AgentLocation>>,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl LettingAgentRow {
    pub fn from_parts(source: crate::accounts::letting_agent::LettingAgent, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            wallet: source.wallet.into(),
            region_id: source.region_id.into(),
            locations: sqlx::types::Json(source.locations.into_iter().map(|element| element.into()).collect()),
            rent_payer: source.rent_payer.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<LettingAgentRow> for crate::accounts::letting_agent::LettingAgent {
    type Error = carbon_core::error::Error;
    fn try_from(source: LettingAgentRow) -> Result<Self, Self::Error> {
        Ok(Self {
            wallet: *source.wallet,
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            locations: source.locations.0,
            rent_payer: *source.rent_payer,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::letting_agent::LettingAgent {
    fn table() -> &'static str {
        "letting_agent_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "wallet",
            "region_id",
            "locations",
            "rent_payer",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for LettingAgentRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO letting_agent_account (
                "wallet",
                "region_id",
                "locations",
                "rent_payer",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.wallet.clone())
        .bind(self.region_id.clone())
        .bind(self.locations.clone())
        .bind(self.rent_payer.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for LettingAgentRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO letting_agent_account (
                "wallet",
                "region_id",
                "locations",
                "rent_payer",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "wallet" = EXCLUDED."wallet",
                "region_id" = EXCLUDED."region_id",
                "locations" = EXCLUDED."locations",
                "rent_payer" = EXCLUDED."rent_payer",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.wallet.clone())
        .bind(self.region_id.clone())
        .bind(self.locations.clone())
        .bind(self.rent_payer.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for LettingAgentRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM letting_agent_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for LettingAgentRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM letting_agent_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct LettingAgentMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for LettingAgentMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS letting_agent_account (
                -- Account data
                "wallet" BYTEA NOT NULL,
                "region_id" INT4 NOT NULL,
                "locations" JSONB NOT NULL,
                "rent_payer" BYTEA NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS letting_agent_account"#).execute(connection).await?;
        Ok(())
    }
}
