//! This code was AUTOGENERATED using the Codama library.
pub mod agent_candidacy_row;
pub mod agent_vote_row;
pub mod config_row;
pub mod letting_agent_row;
pub mod property_letting_row;
pub mod resignation_notice_row;

pub use self::agent_candidacy_row::*;
pub use self::agent_vote_row::*;
pub use self::config_row::*;
pub use self::letting_agent_row::*;
pub use self::property_letting_row::*;
pub use self::resignation_notice_row::*;

use super::PropertyAccount;

pub struct PropertyAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for PropertyAccountsMigration {
    fn app(&self) -> &str {
        "property"
    }

    fn name(&self) -> &str {
        "property_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AgentCandidacyMigrationOperation),
            Box::new(AgentVoteMigrationOperation),
            Box::new(ConfigMigrationOperation),
            Box::new(LettingAgentMigrationOperation),
            Box::new(PropertyLettingMigrationOperation),
            Box::new(ResignationNoticeMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct PropertyAccountWithMetadata(pub PropertyAccount, pub carbon_core::account::AccountMetadata);

impl From<(PropertyAccount, carbon_core::account::AccountMetadata)> for PropertyAccountWithMetadata {
    fn from(value: (PropertyAccount, carbon_core::account::AccountMetadata)) -> Self {
        PropertyAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for PropertyAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PropertyAccountWithMetadata(account, metadata) = self;

        match account {
            PropertyAccount::AgentCandidacy(account) => {
                let row = agent_candidacy_row::AgentCandidacyRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PropertyAccount::AgentVote(account) => {
                let row = agent_vote_row::AgentVoteRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PropertyAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PropertyAccount::LettingAgent(account) => {
                let row = letting_agent_row::LettingAgentRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PropertyAccount::PropertyLetting(account) => {
                let row = property_letting_row::PropertyLettingRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            PropertyAccount::ResignationNotice(account) => {
                let row = resignation_notice_row::ResignationNoticeRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for PropertyAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let PropertyAccountWithMetadata(account, metadata) = self;
        match account {
            PropertyAccount::AgentCandidacy(account) => {
                let row = agent_candidacy_row::AgentCandidacyRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PropertyAccount::AgentVote(account) => {
                let row = agent_vote_row::AgentVoteRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PropertyAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PropertyAccount::LettingAgent(account) => {
                let row = letting_agent_row::LettingAgentRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PropertyAccount::PropertyLetting(account) => {
                let row = property_letting_row::PropertyLettingRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            PropertyAccount::ResignationNotice(account) => {
                let row = resignation_notice_row::ResignationNoticeRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}

