//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ClaimSpvCase")]
pub struct ClaimSpvCaseGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub listing_id: U64,
    pub round: U64,
    pub costs: U64,
}

impl TryFrom<crate::instructions::postgres::ClaimSpvCaseRow> for ClaimSpvCaseGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ClaimSpvCaseRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            listing_id: carbon_core::graphql::primitives::U64(*row.listing_id),
            round: carbon_core::graphql::primitives::U64(*row.round),
            costs: carbon_core::graphql::primitives::U64(*row.costs),
        })
    }
}
