//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ExecuteDeal")]
pub struct ExecuteDealGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub listing_id: U64,
}

impl TryFrom<crate::instructions::postgres::ExecuteDealRow> for ExecuteDealGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ExecuteDealRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            listing_id: carbon_core::graphql::primitives::U64(*row.listing_id),
        })
    }
}
