//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::ConfigParamsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeConfig")]
pub struct InitializeConfigGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub params: ConfigParamsGraphQL,
}

impl TryFrom<crate::instructions::postgres::InitializeConfigRow> for InitializeConfigGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::InitializeConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            params: row.params.0.into(),
        })
    }
}
