//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LawyerConfirmDocuments")]
pub struct LawyerConfirmDocumentsGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub listing_id: U64,
    pub approve: bool,
    pub documents_hash: Vec<U8>,
}

impl TryFrom<crate::instructions::postgres::LawyerConfirmDocumentsRow> for LawyerConfirmDocumentsGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::LawyerConfirmDocumentsRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            listing_id: carbon_core::graphql::primitives::U64(*row.listing_id),
            approve: row.approve,
            documents_hash: row.documents_hash.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
        })
    }
}
