//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RegisterLawyer")]
pub struct RegisterLawyerGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub region_id: i32,
    pub max_deposit: U64,
}

impl TryFrom<crate::instructions::postgres::RegisterLawyerRow> for RegisterLawyerGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::RegisterLawyerRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            region_id: (*row.region_id) as i32,
            max_deposit: carbon_core::graphql::primitives::U64(*row.max_deposit),
        })
    }
}
