//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RejectOffer")]
pub struct RejectOfferGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub id: U64,
    pub nonce: U64,
}

impl TryFrom<crate::instructions::postgres::RejectOfferRow> for RejectOfferGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::RejectOfferRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            id: carbon_core::graphql::primitives::U64(*row.id),
            nonce: carbon_core::graphql::primitives::U64(*row.nonce),
        })
    }
}
