//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ReserveShares")]
pub struct ReserveSharesGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub listing_id: U64,
    pub amount: U32,
    pub max_total_cost: U64,
}

impl TryFrom<crate::instructions::postgres::ReserveSharesRow> for ReserveSharesGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ReserveSharesRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            listing_id: carbon_core::graphql::primitives::U64(*row.listing_id),
            amount: carbon_core::graphql::primitives::U32((*row.amount) as u32),
            max_total_cost: carbon_core::graphql::primitives::U64(*row.max_total_cost),
        })
    }
}
