//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VoteOnSpvLawyer")]
pub struct VoteOnSpvLawyerGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub listing_id: U64,
    pub amount: U32,
}

impl TryFrom<crate::instructions::postgres::VoteOnSpvLawyerRow> for VoteOnSpvLawyerGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::VoteOnSpvLawyerRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            listing_id: carbon_core::graphql::primitives::U64(*row.listing_id),
            amount: carbon_core::graphql::primitives::U32((*row.amount) as u32),
        })
    }
}
