//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ClearRegionState")]
pub struct ClearRegionStateGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub region_id: i32,
}

impl TryFrom<crate::instructions::postgres::ClearRegionStateRow> for ClearRegionStateGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ClearRegionStateRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            region_id: (*row.region_id) as i32,
        })
    }
}
