//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CreateRegion")]
pub struct CreateRegionGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub region_id: i32,
    pub listing_duration: I64,
    pub tax_bps: i32,
}

impl TryFrom<crate::instructions::postgres::CreateRegionRow> for CreateRegionGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::CreateRegionRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            region_id: (*row.region_id) as i32,
            listing_duration: carbon_core::graphql::primitives::I64(row.listing_duration),
            tax_bps: (*row.tax_bps) as i32,
        })
    }
}
