//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FaucetReceipt")]
pub struct FaucetReceiptGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub last_drip: I64,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::FaucetReceiptRow> for FaucetReceiptGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::FaucetReceiptRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            last_drip: carbon_core::graphql::primitives::I64(row.last_drip),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
