# syntax=docker/dockerfile:1.7
# Multi-stage cargo-chef build for the Carbon migration's two Rust binaries
# (`crates/indexer`, `crates/api`), sharing one dependency-cached builder stage.
# Build one target at a time via `--target indexer` / `--target api`
# (docker-compose.yml's `build.target` does this for each service).
#
# Usage:
#   docker build -f docker/rust.Dockerfile --target indexer -t indexer:local .
#   docker build -f docker/rust.Dockerfile --target api     -t indexer-api:local .
#
# --------------------------------------------------------------------------------------
# protoc choice (task-7-brief.md asks this to be checked and documented):
#
# `crates/indexer` depends on `carbon-yellowstone-grpc-datasource`, which pulls in
# `yellowstone-grpc-proto`. Its build.rs (verified directly in the vendored source,
# yellowstone-grpc-proto-10.1.1/build.rs) does:
#
#     std::env::set_var("PROTOC", protobuf_src::protoc());
#
# unconditionally, BEFORE compiling geyser.proto -- so simply installing a system protoc
# and exporting a PROTOC env var has NO effect; it is overwritten before it would ever be
# read. `protobuf_src::protoc()` (protobuf-src-1.1.0+21.5/src/lib.rs) always points at a
# vendored protobuf 3.19.1 that ITS OWN build.rs compiles from source via autotools --
# again unconditionally (protobuf-src-1.1.0+21.5/build.rs just runs
# `autotools::Config::new("protobuf").build()`, no existing-protoc check of any kind).
# That vendored compile is what task-3-report.md calls "works but slow" on Linux (on
# Windows it doesn't work at all -- see that report -- but this Dockerfile only ever
# builds on Linux).
#
# The actual bypass is a different, fully-stable Cargo mechanism: `protobuf-src`
# declares `links = "protobuf-src"` in its Cargo.toml, which makes it eligible for
# Cargo's "Overriding Build Scripts" feature
# (https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts)
# -- a `[target.<triple>.protobuf-src]` section in `.cargo/config.toml` REPLACES the
# build script's execution outright (it never runs), supplying the `rustc-env`s it would
# have emitted directly. `protobuf_src::protoc()`/`::include()` read exactly
# `$INSTALL_DIR/bin/protoc` and `$INSTALL_DIR/include`, which is precisely the layout
# Debian's `protobuf-compiler` + `libprotobuf-dev` packages install to under `/usr` --
# so `INSTALL_DIR=/usr` needs no extra staging. geyser.proto's only external import
# (`google/protobuf/timestamp.proto`) is satisfied by `libprotobuf-dev`. Nothing else in
# the dependency graph links against protobuf-src (checked: it appears exactly once,
# as yellowstone-grpc-proto's own build-dependency, in Cargo.lock), so this override is
# fully scoped to the one crate it is meant for.
#
# This is faster (skips a from-source C++ compile of protobuf entirely) and reliable
# (a documented, stable Cargo feature, not an env-var guess) -- so it is the primary
# path below. If a future yellowstone-grpc-proto/protobuf-src upgrade breaks it (e.g.
# yellowstone-grpc-proto stops calling protobuf_src::protoc(), or protobuf-src changes
# its expected install layout), delete the `.cargo/config.toml` generation step and the
# `protobuf-compiler`/`libprotobuf-dev` install -- protobuf-src's vendored autotools
# build still works unattended on Linux, just slower.
# --------------------------------------------------------------------------------------

FROM lukemathwalker/cargo-chef:latest-rust-1 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
      protobuf-compiler libprotobuf-dev \
    && rm -rf /var/lib/apt/lists/*
# See the protoc-choice note above: this bypasses protobuf-src's vendored autotools
# build entirely via Cargo's build-script-override mechanism.
RUN target="$(rustc -vV | sed -n 's/^host: //p')" \
    && mkdir -p .cargo \
    && printf '[target.%s.protobuf-src]\nrustc-env = { INSTALL_DIR = "/usr" }\n' "$target" \
       > .cargo/config.toml \
    && cat .cargo/config.toml
COPY --from=planner /app/recipe.json recipe.json
# `crates/whitelist-decoder` carries its OWN `[workspace]` table (see the root Cargo.toml's
# comment -- generated by `carbon-cli`, cannot be a member of this workspace), so it is a
# path dependency to a package outside the workspace `cargo chef prepare` skeletonized.
# `cargo chef cook` cannot reconstruct it from `recipe.json` alone (verified empirically:
# without this, `cook` fails with "failed to read `/app/crates/whitelist-decoder/Cargo.toml`
# ... No such file or directory") and needs the real files -- copy just that crate ahead of
# `cook` so the dependency layer still only rebuilds when it (or recipe.json) changes, not on
# every source edit under crates/indexer or crates/api.
COPY crates/whitelist-decoder crates/whitelist-decoder
# Dependency layer, cached across builds unless Cargo.toml/Cargo.lock/whitelist-decoder change.
# BuildKit cache mounts (registry downloads + incremental target/) survive even when the
# Dockerfile-layer cache above them is invalidated (e.g. by an application source change) --
# without them every crates.io fetch and every dependency compile would redo from zero on
# each `docker compose up --build`, not just on a Cargo.toml/Cargo.lock change. `target/` is
# a cache mount, so it is NOT part of the image filesystem after the RUN -- the final `cargo
# build` step below copies the two binaries out to an ordinary layer path before it ends.
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --release -p indexer -p api \
    && mkdir -p /out \
    && cp target/release/indexer target/release/api /out/

# ----------------------------------------------------------------------------------------
# Final stages: debian-slim + ca-certificates (for outbound TLS to Alchemy/Postgres) +
# curl (every service's healthcheck in docker-compose.yml curls its own HTTP endpoint --
# task-7-brief.md requires this to actually work, not just be present).
# ----------------------------------------------------------------------------------------

FROM debian:bookworm-slim AS runtime-base
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

FROM runtime-base AS indexer
COPY --from=builder /out/indexer /usr/local/bin/indexer
ENTRYPOINT ["indexer"]
CMD ["run"]

FROM runtime-base AS api
COPY --from=builder /out/api /usr/local/bin/api
ENTRYPOINT ["api"]
