//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CloseIncomeCheckpoint {
    pub asset_id: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CloseIncomeCheckpointInstructionAccounts {
    pub holder: solana_pubkey::Pubkey,
    pub rent_payer: solana_pubkey::Pubkey,
    pub checkpoint: solana_pubkey::Pubkey,
    pub holding: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CloseIncomeCheckpoint {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[178, 97, 236, 81, 222, 159, 104, 227] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CloseIncomeCheckpoint {
    type ArrangedAccounts = CloseIncomeCheckpointInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let holder = next_account(&mut iter)?;
        let rent_payer = next_account(&mut iter)?;
        let checkpoint = next_account(&mut iter)?;
        let holding = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CloseIncomeCheckpointInstructionAccounts {
            holder,
            rent_payer,
            checkpoint,
            holding,
            remaining: remaining.to_vec(),
        })
    }
}
