//! This code was AUTOGENERATED using the Codama library.

use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
pub use super::super::events;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, carbon_core::borsh::BorshSerialize, carbon_core::borsh::BorshDeserialize, PartialEq)]
pub enum CpiEvent {
    AgentCandidacyClaimed(events::agent_candidacy_claimed::AgentCandidacyClaimedEvent),
    AgentCandidacyClosed(events::agent_candidacy_closed::AgentCandidacyClosedEvent),
    AgentElectionFinalized(events::agent_election_finalized::AgentElectionFinalizedEvent),
    AgentResignationFinalized(events::agent_resignation_finalized::AgentResignationFinalizedEvent),
    AgentResignationInitiated(events::agent_resignation_initiated::AgentResignationInitiatedEvent),
    AgentVoteCast(events::agent_vote_cast::AgentVoteCastEvent),
    AgentVotesUnlocked(events::agent_votes_unlocked::AgentVotesUnlockedEvent),
    AuthorityUpdateProposed(events::authority_update_proposed::AuthorityUpdateProposedEvent),
    AuthorityUpdated(events::authority_updated::AuthorityUpdatedEvent),
    ChallengeFinalized(events::challenge_finalized::ChallengeFinalizedEvent),
    ChallengeOpened(events::challenge_opened::ChallengeOpenedEvent),
    ChallengeVoteCast(events::challenge_vote_cast::ChallengeVoteCastEvent),
    ChallengeVotesUnlocked(events::challenge_votes_unlocked::ChallengeVotesUnlockedEvent),
    ConfigInitialized(events::config_initialized::ConfigInitializedEvent),
    ConfigUpdated(events::config_updated::ConfigUpdatedEvent),
    IncomeCheckpointClosed(events::income_checkpoint_closed::IncomeCheckpointClosedEvent),
    IncomeClaimed(events::income_claimed::IncomeClaimedEvent),
    IncomeDistributed(events::income_distributed::IncomeDistributedEvent),
    IncomeSettled(events::income_settled::IncomeSettledEvent),
    LettingAgentAdded(events::letting_agent_added::LettingAgentAddedEvent),
    LettingAgentRemoved(events::letting_agent_removed::LettingAgentRemovedEvent),
    ProposalCreated(events::proposal_created::ProposalCreatedEvent),
    ProposalExecuted(events::proposal_executed::ProposalExecutedEvent),
    ProposalFinalized(events::proposal_finalized::ProposalFinalizedEvent),
    ProposalVoteCast(events::proposal_vote_cast::ProposalVoteCastEvent),
    ProposalVotesUnlocked(events::proposal_votes_unlocked::ProposalVotesUnlockedEvent),
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CpiEventInstructionAccounts {
    pub program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CpiEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[228, 69, 165, 46, 81, 203, 154, 29] {
            return None;
        }

        let event_data = &data[8..];

                if let Some(decoded) = events::agent_candidacy_claimed::AgentCandidacyClaimedEvent::decode(event_data) {
            return Some(CpiEvent::AgentCandidacyClaimed(decoded));
        }
                if let Some(decoded) = events::agent_candidacy_closed::AgentCandidacyClosedEvent::decode(event_data) {
            return Some(CpiEvent::AgentCandidacyClosed(decoded));
        }
                if let Some(decoded) = events::agent_election_finalized::AgentElectionFinalizedEvent::decode(event_data) {
            return Some(CpiEvent::AgentElectionFinalized(decoded));
        }
                if let Some(decoded) = events::agent_resignation_finalized::AgentResignationFinalizedEvent::decode(event_data) {
            return Some(CpiEvent::AgentResignationFinalized(decoded));
        }
                if let Some(decoded) = events::agent_resignation_initiated::AgentResignationInitiatedEvent::decode(event_data) {
            return Some(CpiEvent::AgentResignationInitiated(decoded));
        }
                if let Some(decoded) = events::agent_vote_cast::AgentVoteCastEvent::decode(event_data) {
            return Some(CpiEvent::AgentVoteCast(decoded));
        }
                if let Some(decoded) = events::agent_votes_unlocked::AgentVotesUnlockedEvent::decode(event_data) {
            return Some(CpiEvent::AgentVotesUnlocked(decoded));
        }
                if let Some(decoded) = events::authority_update_proposed::AuthorityUpdateProposedEvent::decode(event_data) {
            return Some(CpiEvent::AuthorityUpdateProposed(decoded));
        }
                if let Some(decoded) = events::authority_updated::AuthorityUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::AuthorityUpdated(decoded));
        }
                if let Some(decoded) = events::challenge_finalized::ChallengeFinalizedEvent::decode(event_data) {
            return Some(CpiEvent::ChallengeFinalized(decoded));
        }
                if let Some(decoded) = events::challenge_opened::ChallengeOpenedEvent::decode(event_data) {
            return Some(CpiEvent::ChallengeOpened(decoded));
        }
                if let Some(decoded) = events::challenge_vote_cast::ChallengeVoteCastEvent::decode(event_data) {
            return Some(CpiEvent::ChallengeVoteCast(decoded));
        }
                if let Some(decoded) = events::challenge_votes_unlocked::ChallengeVotesUnlockedEvent::decode(event_data) {
            return Some(CpiEvent::ChallengeVotesUnlocked(decoded));
        }
                if let Some(decoded) = events::config_initialized::ConfigInitializedEvent::decode(event_data) {
            return Some(CpiEvent::ConfigInitialized(decoded));
        }
                if let Some(decoded) = events::config_updated::ConfigUpdatedEvent::decode(event_data) {
            return Some(CpiEvent::ConfigUpdated(decoded));
        }
                if let Some(decoded) = events::income_checkpoint_closed::IncomeCheckpointClosedEvent::decode(event_data) {
            return Some(CpiEvent::IncomeCheckpointClosed(decoded));
        }
                if let Some(decoded) = events::income_claimed::IncomeClaimedEvent::decode(event_data) {
            return Some(CpiEvent::IncomeClaimed(decoded));
        }
                if let Some(decoded) = events::income_distributed::IncomeDistributedEvent::decode(event_data) {
            return Some(CpiEvent::IncomeDistributed(decoded));
        }
                if let Some(decoded) = events::income_settled::IncomeSettledEvent::decode(event_data) {
            return Some(CpiEvent::IncomeSettled(decoded));
        }
                if let Some(decoded) = events::letting_agent_added::LettingAgentAddedEvent::decode(event_data) {
            return Some(CpiEvent::LettingAgentAdded(decoded));
        }
                if let Some(decoded) = events::letting_agent_removed::LettingAgentRemovedEvent::decode(event_data) {
            return Some(CpiEvent::LettingAgentRemoved(decoded));
        }
                if let Some(decoded) = events::proposal_created::ProposalCreatedEvent::decode(event_data) {
            return Some(CpiEvent::ProposalCreated(decoded));
        }
                if let Some(decoded) = events::proposal_executed::ProposalExecutedEvent::decode(event_data) {
            return Some(CpiEvent::ProposalExecuted(decoded));
        }
                if let Some(decoded) = events::proposal_finalized::ProposalFinalizedEvent::decode(event_data) {
            return Some(CpiEvent::ProposalFinalized(decoded));
        }
                if let Some(decoded) = events::proposal_vote_cast::ProposalVoteCastEvent::decode(event_data) {
            return Some(CpiEvent::ProposalVoteCast(decoded));
        }
                if let Some(decoded) = events::proposal_votes_unlocked::ProposalVotesUnlockedEvent::decode(event_data) {
            return Some(CpiEvent::ProposalVotesUnlocked(decoded));
        }
                None
    }
}

impl ArrangeAccounts for CpiEvent {
    type ArrangedAccounts = CpiEventInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let [program, event_authority, remaining @ ..] = accounts else {
            return None;
        };

        Some(CpiEventInstructionAccounts {
            program: program.pubkey,
            event_authority: event_authority.pubkey,
            remaining: remaining.to_vec(),
        })
    }
}

