//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct DistributeIncome {
    pub asset_id: u64,
    pub amount: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DistributeIncomeInstructionAccounts {
    pub agent: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub agent_role: solana_pubkey::Pubkey,
    pub letting: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub market_config: solana_pubkey::Pubkey,
    pub income: solana_pubkey::Pubkey,
    pub payment_mint: solana_pubkey::Pubkey,
    pub agent_payment: solana_pubkey::Pubkey,
    pub income_vault: solana_pubkey::Pubkey,
    pub vault_payment_account: solana_pubkey::Pubkey,
    pub payment_token_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl DistributeIncome {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[81, 17, 61, 96, 242, 93, 210, 51] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for DistributeIncome {
    type ArrangedAccounts = DistributeIncomeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let agent = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let agent_role = next_account(&mut iter)?;
        let letting = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let market_config = next_account(&mut iter)?;
        let income = next_account(&mut iter)?;
        let payment_mint = next_account(&mut iter)?;
        let agent_payment = next_account(&mut iter)?;
        let income_vault = next_account(&mut iter)?;
        let vault_payment_account = next_account(&mut iter)?;
        let payment_token_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(DistributeIncomeInstructionAccounts {
            agent,
            payer,
            agent_role,
            letting,
            property,
            market_config,
            income,
            payment_mint,
            agent_payment,
            income_vault,
            vault_payment_account,
            payment_token_program,
            associated_token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
