//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct FinalizeAgentElection {
    pub asset_id: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FinalizeAgentElectionInstructionAccounts {
    pub cranker: solana_pubkey::Pubkey,
    pub letting: solana_pubkey::Pubkey,
    pub property: solana_pubkey::Pubkey,
    pub winner_entry: Option<solana_pubkey::Pubkey>,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl FinalizeAgentElection {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[48, 143, 199, 27, 97, 168, 117, 123] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for FinalizeAgentElection {
    type ArrangedAccounts = FinalizeAgentElectionInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let cranker = next_account(&mut iter)?;
        let letting = next_account(&mut iter)?;
        let property = next_account(&mut iter)?;
        let winner_entry = next_account(&mut iter);

        let remaining = iter.as_slice();

        Some(FinalizeAgentElectionInstructionAccounts {
            cranker,
            letting,
            property,
            winner_entry,
            remaining: remaining.to_vec(),
        })
    }
}
