//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::PropertyDecoder;
#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod accept_authority;
pub mod add_letting_agent;
pub mod claim_property;
pub mod close_agent_candidacy;
pub mod finalize_agent_election;
pub mod finalize_resignation;
pub mod initialize_config;
pub mod remove_letting_agent;
pub mod resign;
pub mod unlock_agent_votes;
pub mod update_authority;
pub mod update_config;
pub mod vote_on_agent;
pub mod cpi_event;

pub use self::accept_authority::*;
pub use self::add_letting_agent::*;
pub use self::claim_property::*;
pub use self::close_agent_candidacy::*;
pub use self::finalize_agent_election::*;
pub use self::finalize_resignation::*;
pub use self::initialize_config::*;
pub use self::remove_letting_agent::*;
pub use self::resign::*;
pub use self::unlock_agent_votes::*;
pub use self::update_authority::*;
pub use self::update_config::*;
pub use self::vote_on_agent::*;
pub use self::cpi_event::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PropertyInstruction {
    AcceptAuthority(AcceptAuthority),
    AddLettingAgent(AddLettingAgent),
    ClaimProperty(ClaimProperty),
    CloseAgentCandidacy(CloseAgentCandidacy),
    FinalizeAgentElection(FinalizeAgentElection),
    FinalizeResignation(FinalizeResignation),
    InitializeConfig(InitializeConfig),
    RemoveLettingAgent(RemoveLettingAgent),
    Resign(Resign),
    UnlockAgentVotes(UnlockAgentVotes),
    UpdateAuthority(UpdateAuthority),
    UpdateConfig(UpdateConfig),
    VoteOnAgent(VoteOnAgent),
    // Anchor CPI Event Instruction
    CpiEvent(CpiEvent)
}

impl carbon_core::instruction::InstructionDecoder<'_> for PropertyDecoder {
    type InstructionType = PropertyInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = accept_authority::AcceptAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::AcceptAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = add_letting_agent::AddLettingAgent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::AddLettingAgent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_property::ClaimProperty::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::ClaimProperty(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = close_agent_candidacy::CloseAgentCandidacy::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::CloseAgentCandidacy(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = finalize_agent_election::FinalizeAgentElection::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::FinalizeAgentElection(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = finalize_resignation::FinalizeResignation::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::FinalizeResignation(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize_config::InitializeConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::InitializeConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_letting_agent::RemoveLettingAgent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::RemoveLettingAgent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = resign::Resign::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::Resign(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = unlock_agent_votes::UnlockAgentVotes::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::UnlockAgentVotes(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_authority::UpdateAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::UpdateAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_config::UpdateConfig::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::UpdateConfig(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = vote_on_agent::VoteOnAgent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::VoteOnAgent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PropertyInstruction::CpiEvent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
