//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct RemoveLettingAgent {
    pub postcode: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RemoveLettingAgentInstructionAccounts {
    pub agent: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub agent_entry: solana_pubkey::Pubkey,
    pub rent_receiver: solana_pubkey::Pubkey,
    pub xcav_mint: solana_pubkey::Pubkey,
    pub agent_token: solana_pubkey::Pubkey,
    pub vault: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl RemoveLettingAgent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[182, 25, 229, 250, 10, 26, 241, 235] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for RemoveLettingAgent {
    type ArrangedAccounts = RemoveLettingAgentInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let agent = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let agent_entry = next_account(&mut iter)?;
        let rent_receiver = next_account(&mut iter)?;
        let xcav_mint = next_account(&mut iter)?;
        let agent_token = next_account(&mut iter)?;
        let vault = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(RemoveLettingAgentInstructionAccounts {
            agent,
            config,
            agent_entry,
            rent_receiver,
            xcav_mint,
            agent_token,
            vault,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
