//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::VoteChoice;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct VoteOnChallenge {
    pub asset_id: u64,
    pub choice: VoteChoice,
    pub amount: u32,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct VoteOnChallengeInstructionAccounts {
    pub voter: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub voter_role: solana_pubkey::Pubkey,
    pub letting: solana_pubkey::Pubkey,
    pub challenge: solana_pubkey::Pubkey,
    pub holding: solana_pubkey::Pubkey,
    pub vote_record: solana_pubkey::Pubkey,
    pub cpi_auth: solana_pubkey::Pubkey,
    pub marketplace_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl VoteOnChallenge {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[19, 36, 128, 75, 123, 135, 79, 64] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for VoteOnChallenge {
    type ArrangedAccounts = VoteOnChallengeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let voter = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let voter_role = next_account(&mut iter)?;
        let letting = next_account(&mut iter)?;
        let challenge = next_account(&mut iter)?;
        let holding = next_account(&mut iter)?;
        let vote_record = next_account(&mut iter)?;
        let cpi_auth = next_account(&mut iter)?;
        let marketplace_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(VoteOnChallengeInstructionAccounts {
            voter,
            payer,
            voter_role,
            letting,
            challenge,
            holding,
            vote_record,
            cpi_auth,
            marketplace_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
