//! This code was AUTOGENERATED using the Codama library.

pub mod agent_candidacy_claimed;
pub mod agent_candidacy_closed;
pub mod agent_election_finalized;
pub mod agent_resignation_finalized;
pub mod agent_resignation_initiated;
pub mod agent_vote_cast;
pub mod agent_votes_unlocked;
pub mod authority_updated;
pub mod authority_update_proposed;
pub mod challenge_finalized;
pub mod challenge_opened;
pub mod challenge_vote_cast;
pub mod challenge_votes_unlocked;
pub mod config_initialized;
pub mod config_updated;
pub mod income_checkpoint_closed;
pub mod income_claimed;
pub mod income_distributed;
pub mod income_settled;
pub mod letting_agent_added;
pub mod letting_agent_removed;
pub mod proposal_created;
pub mod proposal_executed;
pub mod proposal_finalized;
pub mod proposal_vote_cast;
pub mod proposal_votes_unlocked;

