//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::TallyGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Challenge")]
pub struct ChallengeGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub asset_id: U64,
    pub id: U64,
    pub challenger: Pubkey,
    pub agent: Pubkey,
    pub deposit: U64,
    pub expiry: I64,
    pub tally: TallyGraphQL,
    pub quorum_bps: i32,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::ChallengeRow> for ChallengeGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::ChallengeRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
            id: carbon_core::graphql::primitives::U64(*row.id),
            challenger: carbon_core::graphql::primitives::Pubkey(row.challenger.0),
            agent: carbon_core::graphql::primitives::Pubkey(row.agent.0),
            deposit: carbon_core::graphql::primitives::U64(*row.deposit),
            expiry: carbon_core::graphql::primitives::I64(row.expiry),
            tally: row.tally.0.into(),
            quorum_bps: (*row.quorum_bps) as i32,
            rent_payer: carbon_core::graphql::primitives::Pubkey(row.rent_payer.0),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
