//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::CheckpointEntryGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "IncomeCheckpoint")]
pub struct IncomeCheckpointGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub asset_id: U64,
    pub owner: Pubkey,
    pub entries: Vec<CheckpointEntryGraphQL>,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::IncomeCheckpointRow> for IncomeCheckpointGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::IncomeCheckpointRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
            owner: carbon_core::graphql::primitives::Pubkey(row.owner.0),
            entries: row.entries.0.into_iter().map(|item| item.into()).collect(),
            rent_payer: carbon_core::graphql::primitives::Pubkey(row.rent_payer.0),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
