//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ResignationNotice")]
pub struct ResignationNoticeGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub asset_id: U64,
    pub agent: Pubkey,
    pub due_ts: I64,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::ResignationNoticeRow> for ResignationNoticeGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::ResignationNoticeRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
            agent: carbon_core::graphql::primitives::Pubkey(row.agent.0),
            due_ts: carbon_core::graphql::primitives::I64(row.due_ts),
            rent_payer: carbon_core::graphql::primitives::Pubkey(row.rent_payer.0),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
