//! This code was AUTOGENERATED using the Codama library.
pub mod config_row;
pub mod location_row;
pub mod region_row;
pub mod region_proposal_row;
pub mod region_state_row;
pub mod vote_record_row;

pub use self::config_row::*;
pub use self::location_row::*;
pub use self::region_row::*;
pub use self::region_proposal_row::*;
pub use self::region_state_row::*;
pub use self::vote_record_row::*;

use super::RegionsAccount;

pub struct RegionsAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for RegionsAccountsMigration {
    fn app(&self) -> &str {
        "regions"
    }

    fn name(&self) -> &str {
        "regions_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(ConfigMigrationOperation),
            Box::new(LocationMigrationOperation),
            Box::new(RegionMigrationOperation),
            Box::new(RegionProposalMigrationOperation),
            Box::new(RegionStateMigrationOperation),
            Box::new(VoteRecordMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct RegionsAccountWithMetadata(pub RegionsAccount, pub carbon_core::account::AccountMetadata);

impl From<(RegionsAccount, carbon_core::account::AccountMetadata)> for RegionsAccountWithMetadata {
    fn from(value: (RegionsAccount, carbon_core::account::AccountMetadata)) -> Self {
        RegionsAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RegionsAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RegionsAccountWithMetadata(account, metadata) = self;

        match account {
            RegionsAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsAccount::Location(account) => {
                let row = location_row::LocationRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsAccount::Region(account) => {
                let row = region_row::RegionRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsAccount::RegionProposal(account) => {
                let row = region_proposal_row::RegionProposalRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsAccount::RegionState(account) => {
                let row = region_state_row::RegionStateRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsAccount::VoteRecord(account) => {
                let row = vote_record_row::VoteRecordRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RegionsAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RegionsAccountWithMetadata(account, metadata) = self;
        match account {
            RegionsAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsAccount::Location(account) => {
                let row = location_row::LocationRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsAccount::Region(account) => {
                let row = region_row::RegionRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsAccount::RegionProposal(account) => {
                let row = region_proposal_row::RegionProposalRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsAccount::RegionState(account) => {
                let row = region_state_row::RegionStateRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsAccount::VoteRecord(account) => {
                let row = vote_record_row::VoteRecordRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}

