//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;
use carbon_core::postgres::primitives::U8;
use crate::types::RegionStatus;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct RegionStateRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub region_id: U16,
    pub status: sqlx::types::Json<RegionStatus>,
    pub proposal_id: U64,
    pub proposer: Pubkey,
    pub deposit: U64,
    pub claim_deadline: i64,
    pub bump: U8,
}

impl RegionStateRow {
    pub fn from_parts(source: crate::accounts::region_state::RegionState, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            region_id: source.region_id.into(),
            status: sqlx::types::Json(source.status.into()),
            proposal_id: source.proposal_id.into(),
            proposer: source.proposer.into(),
            deposit: source.deposit.into(),
            claim_deadline: source.claim_deadline.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<RegionStateRow> for crate::accounts::region_state::RegionState {
    type Error = carbon_core::error::Error;
    fn try_from(source: RegionStateRow) -> Result<Self, Self::Error> {
        Ok(Self {
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            status: source.status.0,
            proposal_id: *source.proposal_id,
            proposer: *source.proposer,
            deposit: *source.deposit,
            claim_deadline: source.claim_deadline.into(),
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::region_state::RegionState {
    fn table() -> &'static str {
        "region_state_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "region_id",
            "status",
            "proposal_id",
            "proposer",
            "deposit",
            "claim_deadline",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RegionStateRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO region_state_account (
                "region_id",
                "status",
                "proposal_id",
                "proposer",
                "deposit",
                "claim_deadline",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            )"#)
        .bind(self.region_id.clone())
        .bind(self.status.clone())
        .bind(self.proposal_id.clone())
        .bind(self.proposer.clone())
        .bind(self.deposit.clone())
        .bind(self.claim_deadline.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RegionStateRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO region_state_account (
                "region_id",
                "status",
                "proposal_id",
                "proposer",
                "deposit",
                "claim_deadline",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "region_id" = EXCLUDED."region_id",
                "status" = EXCLUDED."status",
                "proposal_id" = EXCLUDED."proposal_id",
                "proposer" = EXCLUDED."proposer",
                "deposit" = EXCLUDED."deposit",
                "claim_deadline" = EXCLUDED."claim_deadline",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.region_id.clone())
        .bind(self.status.clone())
        .bind(self.proposal_id.clone())
        .bind(self.proposer.clone())
        .bind(self.deposit.clone())
        .bind(self.claim_deadline.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for RegionStateRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM region_state_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for RegionStateRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM region_state_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct RegionStateMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for RegionStateMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS region_state_account (
                -- Account data
                "region_id" INT4 NOT NULL,
                "status" JSONB NOT NULL,
                "proposal_id" NUMERIC(20) NOT NULL,
                "proposer" BYTEA NOT NULL,
                "deposit" NUMERIC(20) NOT NULL,
                "claim_deadline" INT8 NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS region_state_account"#).execute(connection).await?;
        Ok(())
    }
}
