//! This code was AUTOGENERATED using the Codama library.
pub mod accept_authority_row;
pub mod add_admin_row;
pub mod assign_role_row;
pub mod initialize_config_row;
pub mod remove_admin_row;
pub mod remove_role_row;
pub mod renounce_role_row;
pub mod set_permission_row;
pub mod update_authority_row;
pub mod cpi_event_row;

pub use self::accept_authority_row::*;
pub use self::add_admin_row::*;
pub use self::assign_role_row::*;
pub use self::initialize_config_row::*;
pub use self::remove_admin_row::*;
pub use self::remove_role_row::*;
pub use self::renounce_role_row::*;
pub use self::set_permission_row::*;
pub use self::update_authority_row::*;
pub use self::cpi_event_row::*;

use super::XcavateWhitelistInstruction;

pub struct XcavateWhitelistInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for XcavateWhitelistInstructionsMigration {
    fn app(&self) -> &str {
        "xcavate-whitelist"
    }

    fn name(&self) -> &str {
        "xcavate_whitelist_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AcceptAuthorityMigrationOperation),
            Box::new(AddAdminMigrationOperation),
            Box::new(AssignRoleMigrationOperation),
            Box::new(InitializeConfigMigrationOperation),
            Box::new(RemoveAdminMigrationOperation),
            Box::new(RemoveRoleMigrationOperation),
            Box::new(RenounceRoleMigrationOperation),
            Box::new(SetPermissionMigrationOperation),
            Box::new(UpdateAuthorityMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct XcavateWhitelistInstructionWithMetadata(pub XcavateWhitelistInstruction, pub carbon_core::instruction::InstructionMetadata);

impl From<(XcavateWhitelistInstruction, carbon_core::instruction::InstructionMetadata)> for XcavateWhitelistInstructionWithMetadata {
    fn from(value: (XcavateWhitelistInstruction, carbon_core::instruction::InstructionMetadata)) -> Self {
        XcavateWhitelistInstructionWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for XcavateWhitelistInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let XcavateWhitelistInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            XcavateWhitelistInstruction::AcceptAuthority(instruction) => {
                let row = accept_authority_row::AcceptAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::AddAdmin(instruction) => {
                let row = add_admin_row::AddAdminRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::AssignRole(instruction) => {
                let row = assign_role_row::AssignRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::InitializeConfig(instruction) => {
                let row = initialize_config_row::InitializeConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RemoveAdmin(instruction) => {
                let row = remove_admin_row::RemoveAdminRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RemoveRole(instruction) => {
                let row = remove_role_row::RemoveRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RenounceRole(instruction) => {
                let row = renounce_role_row::RenounceRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::SetPermission(instruction) => {
                let row = set_permission_row::SetPermissionRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::UpdateAuthority(instruction) => {
                let row = update_authority_row::UpdateAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for XcavateWhitelistInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let XcavateWhitelistInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            XcavateWhitelistInstruction::AcceptAuthority(instruction) => {
                let row = accept_authority_row::AcceptAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::AddAdmin(instruction) => {
                let row = add_admin_row::AddAdminRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::AssignRole(instruction) => {
                let row = assign_role_row::AssignRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::InitializeConfig(instruction) => {
                let row = initialize_config_row::InitializeConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RemoveAdmin(instruction) => {
                let row = remove_admin_row::RemoveAdminRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RemoveRole(instruction) => {
                let row = remove_role_row::RemoveRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::RenounceRole(instruction) => {
                let row = renounce_role_row::RenounceRoleRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::SetPermission(instruction) => {
                let row = set_permission_row::SetPermissionRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::UpdateAuthority(instruction) => {
                let row = update_authority_row::UpdateAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            XcavateWhitelistInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
