//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "HubParams")]
pub struct HubParamsGraphQL {
    pub name: String,
    pub per_wallet_cap: U32,
    pub supplier: Pubkey,
    pub operators: Pubkey,
    pub protocol: Pubkey,
}

impl From<crate::types::HubParams> for HubParamsGraphQL {
    fn from(original: crate::types::HubParams) -> Self {
        Self {
            name: original.name,
            per_wallet_cap: carbon_core::graphql::primitives::U32(original.per_wallet_cap),
            supplier: carbon_core::graphql::primitives::Pubkey(original.supplier),
            operators: carbon_core::graphql::primitives::Pubkey(original.operators),
            protocol: carbon_core::graphql::primitives::Pubkey(original.protocol),
        }
    }
}
