//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "IncomeClaimed")]
pub struct IncomeClaimedGraphQL {
    pub hub_id: U64,
    pub holder: Pubkey,
    pub amount: U64,
}

impl From<crate::types::IncomeClaimed> for IncomeClaimedGraphQL {
    fn from(original: crate::types::IncomeClaimed) -> Self {
        Self {
            hub_id: carbon_core::graphql::primitives::U64(original.hub_id),
            holder: carbon_core::graphql::primitives::Pubkey(original.holder),
            amount: carbon_core::graphql::primitives::U64(original.amount),
        }
    }
}
