//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct CreateNewLocationRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub region_id: U16,
    pub postcode: Vec<u8>,
    pub max_deposit: U64,
}

impl CreateNewLocationRow {
    pub fn from_parts(source: crate::instructions::create_new_location::CreateNewLocation, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            region_id: source.region_id.into(),
            postcode: source.postcode.into(),
            max_deposit: source.max_deposit.into(),
        }
    }
}

impl TryFrom<CreateNewLocationRow> for crate::instructions::create_new_location::CreateNewLocation {
    type Error = carbon_core::error::Error;
    fn try_from(source: CreateNewLocationRow) -> Result<Self, Self::Error> {
        Ok(Self {
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            postcode: source.postcode.into(),
            max_deposit: *source.max_deposit,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::create_new_location::CreateNewLocation {
    fn table() -> &'static str {
        "create_new_location_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "region_id",
            "postcode",
            "max_deposit",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CreateNewLocationRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO create_new_location_instruction (
                "region_id",
                "postcode",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.region_id.clone())
        .bind(self.postcode.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CreateNewLocationRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO create_new_location_instruction (
                "region_id",
                "postcode",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "region_id" = EXCLUDED."region_id",
                "postcode" = EXCLUDED."postcode",
                "max_deposit" = EXCLUDED."max_deposit",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.region_id.clone())
        .bind(self.postcode.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for CreateNewLocationRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM create_new_location_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for CreateNewLocationRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM create_new_location_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct CreateNewLocationMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for CreateNewLocationMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS create_new_location_instruction (
                -- Instruction data
                "region_id" INT4 NOT NULL,
                "postcode" BYTEA NOT NULL,
                "max_deposit" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS create_new_location_instruction"#).execute(connection).await?;
        Ok(())
    }
}
