//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct InitiateResignationRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub region_id: U16,
}

impl InitiateResignationRow {
    pub fn from_parts(source: crate::instructions::initiate_resignation::InitiateResignation, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            region_id: source.region_id.into(),
        }
    }
}

impl TryFrom<InitiateResignationRow> for crate::instructions::initiate_resignation::InitiateResignation {
    type Error = carbon_core::error::Error;
    fn try_from(source: InitiateResignationRow) -> Result<Self, Self::Error> {
        Ok(Self {
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::initiate_resignation::InitiateResignation {
    fn table() -> &'static str {
        "initiate_resignation_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "region_id",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for InitiateResignationRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO initiate_resignation_instruction (
                "region_id",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            )"#)
        .bind(self.region_id.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for InitiateResignationRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO initiate_resignation_instruction (
                "region_id",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "region_id" = EXCLUDED."region_id",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.region_id.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for InitiateResignationRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM initiate_resignation_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for InitiateResignationRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM initiate_resignation_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct InitiateResignationMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for InitiateResignationMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS initiate_resignation_instruction (
                -- Instruction data
                "region_id" INT4 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS initiate_resignation_instruction"#).execute(connection).await?;
        Ok(())
    }
}
