//! This code was AUTOGENERATED using the Codama library.
pub mod accept_authority_row;
pub mod adjust_listing_duration_row;
pub mod adjust_region_tax_row;
pub mod claim_open_region_row;
pub mod clear_region_state_row;
pub mod create_new_location_row;
pub mod create_region_row;
pub mod finalize_region_proposal_row;
pub mod initialize_config_row;
pub mod initiate_resignation_row;
pub mod propose_new_region_row;
pub mod remove_location_row;
pub mod unlock_voting_token_row;
pub mod update_authority_row;
pub mod update_config_row;
pub mod vote_on_region_proposal_row;
pub mod cpi_event_row;

pub use self::accept_authority_row::*;
pub use self::adjust_listing_duration_row::*;
pub use self::adjust_region_tax_row::*;
pub use self::claim_open_region_row::*;
pub use self::clear_region_state_row::*;
pub use self::create_new_location_row::*;
pub use self::create_region_row::*;
pub use self::finalize_region_proposal_row::*;
pub use self::initialize_config_row::*;
pub use self::initiate_resignation_row::*;
pub use self::propose_new_region_row::*;
pub use self::remove_location_row::*;
pub use self::unlock_voting_token_row::*;
pub use self::update_authority_row::*;
pub use self::update_config_row::*;
pub use self::vote_on_region_proposal_row::*;
pub use self::cpi_event_row::*;

use super::RegionsInstruction;

pub struct RegionsInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for RegionsInstructionsMigration {
    fn app(&self) -> &str {
        "regions"
    }

    fn name(&self) -> &str {
        "regions_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AcceptAuthorityMigrationOperation),
            Box::new(AdjustListingDurationMigrationOperation),
            Box::new(AdjustRegionTaxMigrationOperation),
            Box::new(ClaimOpenRegionMigrationOperation),
            Box::new(ClearRegionStateMigrationOperation),
            Box::new(CreateNewLocationMigrationOperation),
            Box::new(CreateRegionMigrationOperation),
            Box::new(FinalizeRegionProposalMigrationOperation),
            Box::new(InitializeConfigMigrationOperation),
            Box::new(InitiateResignationMigrationOperation),
            Box::new(ProposeNewRegionMigrationOperation),
            Box::new(RemoveLocationMigrationOperation),
            Box::new(UnlockVotingTokenMigrationOperation),
            Box::new(UpdateAuthorityMigrationOperation),
            Box::new(UpdateConfigMigrationOperation),
            Box::new(VoteOnRegionProposalMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct RegionsInstructionWithMetadata(pub RegionsInstruction, pub carbon_core::instruction::InstructionMetadata);

impl From<(RegionsInstruction, carbon_core::instruction::InstructionMetadata)> for RegionsInstructionWithMetadata {
    fn from(value: (RegionsInstruction, carbon_core::instruction::InstructionMetadata)) -> Self {
        RegionsInstructionWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RegionsInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RegionsInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            RegionsInstruction::AcceptAuthority(instruction) => {
                let row = accept_authority_row::AcceptAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::AdjustListingDuration(instruction) => {
                let row = adjust_listing_duration_row::AdjustListingDurationRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::AdjustRegionTax(instruction) => {
                let row = adjust_region_tax_row::AdjustRegionTaxRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ClaimOpenRegion(instruction) => {
                let row = claim_open_region_row::ClaimOpenRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ClearRegionState(instruction) => {
                let row = clear_region_state_row::ClearRegionStateRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CreateNewLocation(instruction) => {
                let row = create_new_location_row::CreateNewLocationRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CreateRegion(instruction) => {
                let row = create_region_row::CreateRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::FinalizeRegionProposal(instruction) => {
                let row = finalize_region_proposal_row::FinalizeRegionProposalRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::InitializeConfig(instruction) => {
                let row = initialize_config_row::InitializeConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::InitiateResignation(instruction) => {
                let row = initiate_resignation_row::InitiateResignationRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ProposeNewRegion(instruction) => {
                let row = propose_new_region_row::ProposeNewRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::RemoveLocation(instruction) => {
                let row = remove_location_row::RemoveLocationRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UnlockVotingToken(instruction) => {
                let row = unlock_voting_token_row::UnlockVotingTokenRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UpdateAuthority(instruction) => {
                let row = update_authority_row::UpdateAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UpdateConfig(instruction) => {
                let row = update_config_row::UpdateConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::VoteOnRegionProposal(instruction) => {
                let row = vote_on_region_proposal_row::VoteOnRegionProposalRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RegionsInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let RegionsInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            RegionsInstruction::AcceptAuthority(instruction) => {
                let row = accept_authority_row::AcceptAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::AdjustListingDuration(instruction) => {
                let row = adjust_listing_duration_row::AdjustListingDurationRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::AdjustRegionTax(instruction) => {
                let row = adjust_region_tax_row::AdjustRegionTaxRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ClaimOpenRegion(instruction) => {
                let row = claim_open_region_row::ClaimOpenRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ClearRegionState(instruction) => {
                let row = clear_region_state_row::ClearRegionStateRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CreateNewLocation(instruction) => {
                let row = create_new_location_row::CreateNewLocationRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CreateRegion(instruction) => {
                let row = create_region_row::CreateRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::FinalizeRegionProposal(instruction) => {
                let row = finalize_region_proposal_row::FinalizeRegionProposalRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::InitializeConfig(instruction) => {
                let row = initialize_config_row::InitializeConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::InitiateResignation(instruction) => {
                let row = initiate_resignation_row::InitiateResignationRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::ProposeNewRegion(instruction) => {
                let row = propose_new_region_row::ProposeNewRegionRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::RemoveLocation(instruction) => {
                let row = remove_location_row::RemoveLocationRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UnlockVotingToken(instruction) => {
                let row = unlock_voting_token_row::UnlockVotingTokenRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UpdateAuthority(instruction) => {
                let row = update_authority_row::UpdateAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::UpdateConfig(instruction) => {
                let row = update_config_row::UpdateConfigRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::VoteOnRegionProposal(instruction) => {
                let row = vote_on_region_proposal_row::VoteOnRegionProposalRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            RegionsInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
