//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AdminRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub admin: Pubkey,
    pub bump: U8,
}

impl AdminRow {
    pub fn from_parts(source: crate::accounts::admin::Admin, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            admin: source.admin.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<AdminRow> for crate::accounts::admin::Admin {
    type Error = carbon_core::error::Error;
    fn try_from(source: AdminRow) -> Result<Self, Self::Error> {
        Ok(Self {
            admin: *source.admin,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::admin::Admin {
    fn table() -> &'static str {
        "admin_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "admin",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AdminRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO admin_account (
                "admin",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4
            )"#)
        .bind(self.admin.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AdminRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO admin_account (
                "admin",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "admin" = EXCLUDED."admin",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.admin.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AdminRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM admin_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AdminRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM admin_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AdminMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AdminMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS admin_account (
                -- Account data
                "admin" BYTEA NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS admin_account"#).execute(connection).await?;
        Ok(())
    }
}
