//! This code was AUTOGENERATED using the Codama library.

pub mod admin_registered;
pub mod admin_removed;
pub mod authority_updated;
pub mod authority_update_proposed;
pub mod config_initialized;
pub mod permission_updated;
pub mod role_assigned;
pub mod role_removed;

