//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::Tally;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Challenge {
    pub asset_id: u64,
    /// Monotonic per property; vote records are keyed by it.
    pub id: u64,
    pub challenger: Pubkey,
    /// The agent on the seat when the challenge opened; the punishment only
    /// applies while they still hold it.
    pub agent: Pubkey,
    /// The challenger's stake, held in the XCAV vault.
    pub deposit: u64,
    pub expiry: i64,
    pub tally: Tally,
    /// Quorum at the moment the vote opened.
    pub quorum_bps: u16,
    /// The wallet that fronted the account's rent; refunded at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl Challenge {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[119, 250, 161, 121, 119, 81, 22, 208] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
