//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::VoteChoice;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct GovVote {
    pub asset_id: u64,
    /// The proposal or challenge the vote belongs to.
    pub id: u64,
    pub voter: Pubkey,
    pub choice: VoteChoice,
    /// The shares this vote locked and counts for.
    pub power: u32,
    /// The wallet that fronted the record's rent; refunded at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl GovVote {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[159, 187, 29, 31, 84, 97, 194, 42] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
