//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::AgentLocation;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct LettingAgent {
    pub wallet: Pubkey,
    /// The one region this agent covers.
    pub region_id: u16,
    pub locations: Vec<AgentLocation>,
    /// Who funded the account's rent and gets it back at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl LettingAgent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[122, 214, 27, 146, 118, 167, 22, 185] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
