//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::Tally;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Proposal {
    pub asset_id: u64,
    /// Monotonic per property; vote records are keyed by it.
    pub id: u64,
    pub proposer: Pubkey,
    /// What they ask for, in quote units.
    pub amount: u64,
    /// Hash of the off-chain document describing the work.
    pub details_hash: [u8; 32],
    /// When voting closes.
    pub expiry: i64,
    pub tally: Tally,
    /// Quorum and approval threshold at the moment the vote opened, so a
    /// config change can't move the goalposts mid-vote. The threshold is
    /// zero below the high tier.
    pub quorum_bps: u16,
    pub threshold_bps: u16,
    /// The wallet that fronted the account's rent; refunded at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl Proposal {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[26, 94, 189, 187, 116, 136, 53, 33] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
