//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::AgentElection;
use crate::types::GovState;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct PropertyLetting {
    pub asset_id: u64,
    /// The assigned agent; default while the seat is vacant.
    pub agent: Pubkey,
    pub election: AgentElection,
    pub governance: GovState,
    /// The wallet that fronted the account's rent.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl PropertyLetting {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[72, 52, 34, 169, 213, 87, 231, 124] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
