//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct ResignationNotice {
    pub asset_id: u64,
    /// The resigning agent, recorded so the crank can release their
    /// assignment even if the seat's state moves on.
    pub agent: Pubkey,
    /// When the resignation takes effect.
    pub due_ts: i64,
    /// The wallet that fronted the account's rent; refunded at close.
    pub rent_payer: Pubkey,
    pub bump: u8,
}

impl ResignationNotice {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[66, 158, 24, 126, 100, 85, 78, 78] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
