//! This code was AUTOGENERATED using the Codama library.
#[cfg(feature = "graphql")]
pub mod graphql;

pub mod access_permission;
pub mod admin_registered;
pub mod admin_removed;
pub mod authority_updated;
pub mod authority_update_proposed;
pub mod config_initialized;
pub mod permission_updated;
pub mod role;
pub mod role_assigned;
pub mod role_removed;

pub use self::access_permission::*;
pub use self::admin_registered::*;
pub use self::admin_removed::*;
pub use self::authority_updated::*;
pub use self::authority_update_proposed::*;
pub use self::config_initialized::*;
pub use self::permission_updated::*;
pub use self::role::*;
pub use self::role_assigned::*;
pub use self::role_removed::*;

