//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Change how long new listings in the region stay active. Region-operator-only.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct AdjustListingDuration {
    pub region_id: u16,
    pub listing_duration: i64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AdjustListingDurationInstructionAccounts {
    pub operator: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub operator_role: solana_pubkey::Pubkey,
    pub region: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AdjustListingDuration {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[126, 202, 161, 247, 30, 44, 106, 87] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for AdjustListingDuration {
    type ArrangedAccounts = AdjustListingDurationInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let operator = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let operator_role = next_account(&mut iter)?;
        let region = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AdjustListingDurationInstructionAccounts {
            operator,
            config,
            operator_role,
            region,
            remaining: remaining.to_vec(),
        })
    }
}
