//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Register a postcode as a listable location. Region-operator-only;
/// locks a location deposit (capped by `max_deposit`) that joins the
/// region's collateral.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CreateNewLocation {
    pub region_id: u16,
    pub postcode: Vec<u8>,
    pub max_deposit: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateNewLocationInstructionAccounts {
    pub operator: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub operator_role: solana_pubkey::Pubkey,
    pub xcav_mint: solana_pubkey::Pubkey,
    pub operator_token: solana_pubkey::Pubkey,
    pub vault: solana_pubkey::Pubkey,
    pub region: solana_pubkey::Pubkey,
    pub location: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CreateNewLocation {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[249, 10, 147, 55, 102, 73, 248, 87] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CreateNewLocation {
    type ArrangedAccounts = CreateNewLocationInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let operator = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let operator_role = next_account(&mut iter)?;
        let xcav_mint = next_account(&mut iter)?;
        let operator_token = next_account(&mut iter)?;
        let vault = next_account(&mut iter)?;
        let region = next_account(&mut iter)?;
        let location = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CreateNewLocationInstructionAccounts {
            operator,
            config,
            operator_role,
            xcav_mint,
            operator_token,
            vault,
            region,
            location,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
