//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::ConfigParams;

/// Initialize the singleton config with governance parameters.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct InitializeConfig {
    pub params: ConfigParams,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializeConfigInstructionAccounts {
    pub authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub program_data: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub xcav_mint: solana_pubkey::Pubkey,
    pub vault: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl InitializeConfig {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[208, 127, 21, 1, 194, 190, 196, 70] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for InitializeConfig {
    type ArrangedAccounts = InitializeConfigInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;
        let program_data = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let xcav_mint = next_account(&mut iter)?;
        let vault = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitializeConfigInstructionAccounts {
            authority,
            program,
            program_data,
            config,
            xcav_mint,
            vault,
            token_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
