//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// Protocol parameters for the property program.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ConfigParams {
    pub treasury: Pubkey,
    pub rent_collector: Pubkey,
    pub agent_deposit: u64,
    pub agent_voting_time: i64,
    pub min_voting_quorum_bps: u16,
    pub agent_notice_period: i64,
}

