//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// One payment mint's income stream for a property.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct IncomeStream {
    pub mint: Pubkey,
    /// Cumulative income per share since the stream opened, in raw token
    /// units. Wide on purpose: a stream lives as long as the property.
    pub per_share: u128,
    /// Remainder of the last distribution below one unit per share, carried
    /// into the next one so nothing is stranded.
    pub dust: u64,
}

