//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LettingAgentAdded {
    pub agent: Pubkey,
    pub region_id: u16,
    pub postcode: Vec<u8>,
    pub deposit: u64,
}

