//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// The authorization the off-chain payment runs on: the SPV pays this
/// amount from the property's bank account.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ProposalExecuted {
    pub asset_id: u64,
    pub amount: u64,
}

