//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// A fractionalized property. Created when it is listed and kept for the
/// asset's whole life; the Core asset and share mint are attached by
/// `init_property_assets`.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct PropertyAsset {
    pub asset_id: u64,
    /// The Metaplex Core asset held in the property vault. Default until the
    /// assets are initialized.
    pub core_asset: Pubkey,
    /// The Token-2022 share mint. Default until the assets are initialized.
    pub share_mint: Pubkey,
    pub region_id: u16,
    /// The registered location (postcode) the property sits in.
    pub location: Vec<u8>,
    pub share_amount: u32,
    pub spv_created: bool,
    pub finalized: bool,
    /// Wallets currently holding shares; teardown completes when it reaches
    /// zero again.
    pub holder_count: u32,
    pub bump: u8,
}

