//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ProposalCreated {
    pub asset_id: u64,
    pub id: u64,
    pub proposer: Pubkey,
    pub amount: u64,
    pub expiry: i64,
}

