//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use crate::types::VoteChoice;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ProposalVoteCast {
    pub asset_id: u64,
    pub id: u64,
    pub voter: Pubkey,
    pub choice: VoteChoice,
    pub power: u32,
}

