//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ProposalFinalized {
    pub asset_id: u64,
    pub id: u64,
    pub approved: bool,
    pub yes: u32,
    pub no: u32,
    pub abstain: u32,
}

