//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LocationCreated")]
pub struct LocationCreatedGraphQL {
    pub region_id: i32,
    pub postcode: Vec<U8>,
    pub new_collateral: U64,
    pub location_count: U32,
}

impl From<crate::types::LocationCreated> for LocationCreatedGraphQL {
    fn from(original: crate::types::LocationCreated) -> Self {
        Self {
            region_id: original.region_id as i32,
            postcode: original.postcode.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            new_collateral: carbon_core::graphql::primitives::U64(original.new_collateral),
            location_count: carbon_core::graphql::primitives::U32(original.location_count),
        }
    }
}
