//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RegionProposalPassed")]
pub struct RegionProposalPassedGraphQL {
    pub region_id: i32,
    pub proposal_id: U64,
}

impl From<crate::types::RegionProposalPassed> for RegionProposalPassedGraphQL {
    fn from(original: crate::types::RegionProposalPassed) -> Self {
        Self {
            region_id: original.region_id as i32,
            proposal_id: carbon_core::graphql::primitives::U64(original.proposal_id),
        }
    }
}
