//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// Where a region is in its lifecycle before it is created.
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "RegionStatus")]
pub enum RegionStatusGraphQL {
        Proposing,
        Passed,
        Rejected,
}

impl From<crate::types::RegionStatus> for RegionStatusGraphQL {
    fn from(original: crate::types::RegionStatus) -> Self {
        match original {
            crate::types::RegionStatus::Proposing => Self::Proposing,
            crate::types::RegionStatus::Passed => Self::Passed,
            crate::types::RegionStatus::Rejected => Self::Rejected,
        }
    }
}

