//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ResignationInitiated")]
pub struct ResignationInitiatedGraphQL {
    pub region_id: i32,
    pub operator: Pubkey,
    pub next_owner_change: I64,
}

impl From<crate::types::ResignationInitiated> for ResignationInitiatedGraphQL {
    fn from(original: crate::types::ResignationInitiated) -> Self {
        Self {
            region_id: original.region_id as i32,
            operator: carbon_core::graphql::primitives::Pubkey(original.operator),
            next_owner_change: carbon_core::graphql::primitives::I64(original.next_owner_change),
        }
    }
}
