//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VotingTokenUnlocked")]
pub struct VotingTokenUnlockedGraphQL {
    pub proposal_id: U64,
    pub voter: Pubkey,
    pub power: U64,
}

impl From<crate::types::VotingTokenUnlocked> for VotingTokenUnlockedGraphQL {
    fn from(original: crate::types::VotingTokenUnlocked) -> Self {
        Self {
            proposal_id: carbon_core::graphql::primitives::U64(original.proposal_id),
            voter: carbon_core::graphql::primitives::Pubkey(original.voter),
            power: carbon_core::graphql::primitives::U64(original.power),
        }
    }
}
