//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Config")]
pub struct ConfigGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub authority: Pubkey,
    pub pending_authority: Option<Pubkey>,
    pub xcav_mint: Pubkey,
    pub treasury: Pubkey,
    pub rent_collector: Pubkey,
    pub accepted_payment_mints: Vec<Pubkey>,
    pub listing_deposit: U64,
    pub lawyer_deposit: U64,
    pub min_property_shares: U32,
    pub max_property_shares: U32,
    pub marketplace_fee_bps: i32,
    pub investor_fee_bps: i32,
    pub max_ownership_bps: i32,
    pub claiming_time: I64,
    pub legal_process_time: I64,
    pub lawyer_voting_time: I64,
    pub min_voting_quorum_bps: i32,
    pub next_listing_id: U64,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::ConfigRow> for ConfigGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::ConfigRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            authority: carbon_core::graphql::primitives::Pubkey(row.authority.0),
            pending_authority: row.pending_authority.map(|v| carbon_core::graphql::primitives::Pubkey(v.0)),
            xcav_mint: carbon_core::graphql::primitives::Pubkey(row.xcav_mint.0),
            treasury: carbon_core::graphql::primitives::Pubkey(row.treasury.0),
            rent_collector: carbon_core::graphql::primitives::Pubkey(row.rent_collector.0),
            accepted_payment_mints: row.accepted_payment_mints.into_iter().map(|item| carbon_core::graphql::primitives::Pubkey(item.0)).collect(),
            listing_deposit: carbon_core::graphql::primitives::U64(*row.listing_deposit),
            lawyer_deposit: carbon_core::graphql::primitives::U64(*row.lawyer_deposit),
            min_property_shares: carbon_core::graphql::primitives::U32((*row.min_property_shares) as u32),
            max_property_shares: carbon_core::graphql::primitives::U32((*row.max_property_shares) as u32),
            marketplace_fee_bps: (*row.marketplace_fee_bps) as i32,
            investor_fee_bps: (*row.investor_fee_bps) as i32,
            max_ownership_bps: (*row.max_ownership_bps) as i32,
            claiming_time: carbon_core::graphql::primitives::I64(row.claiming_time),
            legal_process_time: carbon_core::graphql::primitives::I64(row.legal_process_time),
            lawyer_voting_time: carbon_core::graphql::primitives::I64(row.lawyer_voting_time),
            min_voting_quorum_bps: (*row.min_voting_quorum_bps) as i32,
            next_listing_id: carbon_core::graphql::primitives::U64(*row.next_listing_id),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
