//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PropertyAsset")]
pub struct PropertyAssetGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub asset_id: U64,
    pub name: String,
    pub metadata_uri: String,
    pub share_mint: Pubkey,
    pub region_id: i32,
    pub location: Vec<U8>,
    pub share_amount: U32,
    pub spv_created: bool,
    pub finalized: bool,
    pub holder_count: U32,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::PropertyAssetRow> for PropertyAssetGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::PropertyAssetRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
            name: row.name,
            metadata_uri: row.metadata_uri,
            share_mint: carbon_core::graphql::primitives::Pubkey(row.share_mint.0),
            region_id: (*row.region_id) as i32,
            location: row.location.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            share_amount: carbon_core::graphql::primitives::U32((*row.share_amount) as u32),
            spv_created: row.spv_created,
            finalized: row.finalized,
            holder_count: carbon_core::graphql::primitives::U32((*row.holder_count) as u32),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
