//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RegionClaimed {
    pub region_id: u16,
    pub new_owner: Pubkey,
    pub collateral: u64,
    pub next_owner_change: i64,
}

