//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RegionTaxChanged {
    pub region_id: u16,
    pub tax_bps: u16,
}

