//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// How a voter can vote on a proposal.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub enum Vote {
    Yes,
    No,
    Abstain,
}

