//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use crate::types::Vote;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct VotedOnRegionProposal {
    pub region_id: u16,
    pub proposal_id: u64,
    pub voter: Pubkey,
    pub vote: Vote,
    pub power: u64,
}

