//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Location {
    pub region_id: u16,
    /// The postcode, as seeded (uppercase ASCII, no spaces).
    pub postcode: Vec<u8>,
    /// The XCAV locked when the location was registered. Released on removal,
    /// even if the configured deposit has changed since.
    pub deposit: u64,
    pub bump: u8,
}

impl Location {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[73, 140, 105, 78, 215, 159, 92, 234] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
