//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U32;
use carbon_core::postgres::primitives::U64;
use carbon_core::postgres::primitives::U8;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct LawyerRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub lawyer: Pubkey,
    pub region_id: U16,
    pub deposit: U64,
    pub active_cases: U32,
    pub bump: U8,
}

impl LawyerRow {
    pub fn from_parts(source: crate::accounts::lawyer::Lawyer, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            lawyer: source.lawyer.into(),
            region_id: source.region_id.into(),
            deposit: source.deposit.into(),
            active_cases: source.active_cases.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<LawyerRow> for crate::accounts::lawyer::Lawyer {
    type Error = carbon_core::error::Error;
    fn try_from(source: LawyerRow) -> Result<Self, Self::Error> {
        Ok(Self {
            lawyer: *source.lawyer,
            region_id: source.region_id.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            deposit: *source.deposit,
            active_cases: source.active_cases.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::lawyer::Lawyer {
    fn table() -> &'static str {
        "lawyer_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "lawyer",
            "region_id",
            "deposit",
            "active_cases",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for LawyerRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO lawyer_account (
                "lawyer",
                "region_id",
                "deposit",
                "active_cases",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.lawyer.clone())
        .bind(self.region_id.clone())
        .bind(self.deposit.clone())
        .bind(self.active_cases.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for LawyerRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO lawyer_account (
                "lawyer",
                "region_id",
                "deposit",
                "active_cases",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "lawyer" = EXCLUDED."lawyer",
                "region_id" = EXCLUDED."region_id",
                "deposit" = EXCLUDED."deposit",
                "active_cases" = EXCLUDED."active_cases",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.lawyer.clone())
        .bind(self.region_id.clone())
        .bind(self.deposit.clone())
        .bind(self.active_cases.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for LawyerRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM lawyer_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for LawyerRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM lawyer_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct LawyerMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for LawyerMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS lawyer_account (
                -- Account data
                "lawyer" BYTEA NOT NULL,
                "region_id" INT4 NOT NULL,
                "deposit" NUMERIC(20) NOT NULL,
                "active_cases" INT8 NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS lawyer_account"#).execute(connection).await?;
        Ok(())
    }
}
