//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U32;
use carbon_core::postgres::primitives::U64;
use carbon_core::postgres::primitives::U8;
use crate::types::CollectedPerMint;
use crate::types::LawyerAssignment;
use crate::types::ListingStatus;
use crate::types::SpvElection;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ListingRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub listing_id: U64,
    pub developer: Pubkey,
    pub asset_id: U64,
    pub share_price: U64,
    pub listed_share_amount: U32,
    pub sold_share_amount: U32,
    pub reserved_share_amount: U32,
    pub tax_paid_by_developer: bool,
    pub tax_bps: U16,
    pub marketplace_fee_bps: U16,
    pub investor_fee_bps: U16,
    pub max_ownership_bps: U16,
    pub listing_expiry: i64,
    pub claiming_time: i64,
    pub claim_deadline: i64,
    pub legal_process_time: i64,
    pub lawyer_voting_time: i64,
    pub min_voting_quorum_bps: U16,
    pub position_count: U32,
    pub legal_deadline: i64,
    pub deposit: U64,
    pub developer_lawyer: sqlx::types::Json<LawyerAssignment>,
    pub spv_lawyer: sqlx::types::Json<LawyerAssignment>,
    pub second_attempt: bool,
    pub developer_engaged: bool,
    pub spv_costs_due: U64,
    pub spv_costs_payee: Pubkey,
    pub collected_fee_quote: U64,
    pub collected: sqlx::types::Json<Vec<CollectedPerMint>>,
    pub spv_election: sqlx::types::Json<SpvElection>,
    pub status: sqlx::types::Json<ListingStatus>,
    pub bump: U8,
}

impl ListingRow {
    pub fn from_parts(source: crate::accounts::listing::Listing, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            listing_id: source.listing_id.into(),
            developer: source.developer.into(),
            asset_id: source.asset_id.into(),
            share_price: source.share_price.into(),
            listed_share_amount: source.listed_share_amount.into(),
            sold_share_amount: source.sold_share_amount.into(),
            reserved_share_amount: source.reserved_share_amount.into(),
            tax_paid_by_developer: source.tax_paid_by_developer.into(),
            tax_bps: source.tax_bps.into(),
            marketplace_fee_bps: source.marketplace_fee_bps.into(),
            investor_fee_bps: source.investor_fee_bps.into(),
            max_ownership_bps: source.max_ownership_bps.into(),
            listing_expiry: source.listing_expiry.into(),
            claiming_time: source.claiming_time.into(),
            claim_deadline: source.claim_deadline.into(),
            legal_process_time: source.legal_process_time.into(),
            lawyer_voting_time: source.lawyer_voting_time.into(),
            min_voting_quorum_bps: source.min_voting_quorum_bps.into(),
            position_count: source.position_count.into(),
            legal_deadline: source.legal_deadline.into(),
            deposit: source.deposit.into(),
            developer_lawyer: sqlx::types::Json(source.developer_lawyer.into()),
            spv_lawyer: sqlx::types::Json(source.spv_lawyer.into()),
            second_attempt: source.second_attempt.into(),
            developer_engaged: source.developer_engaged.into(),
            spv_costs_due: source.spv_costs_due.into(),
            spv_costs_payee: source.spv_costs_payee.into(),
            collected_fee_quote: source.collected_fee_quote.into(),
            collected: sqlx::types::Json(source.collected.into_iter().map(|element| element.into()).collect()),
            spv_election: sqlx::types::Json(source.spv_election.into()),
            status: sqlx::types::Json(source.status.into()),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<ListingRow> for crate::accounts::listing::Listing {
    type Error = carbon_core::error::Error;
    fn try_from(source: ListingRow) -> Result<Self, Self::Error> {
        Ok(Self {
            listing_id: *source.listing_id,
            developer: *source.developer,
            asset_id: *source.asset_id,
            share_price: *source.share_price,
            listed_share_amount: source.listed_share_amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            sold_share_amount: source.sold_share_amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            reserved_share_amount: source.reserved_share_amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            tax_paid_by_developer: source.tax_paid_by_developer.into(),
            tax_bps: source.tax_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            marketplace_fee_bps: source.marketplace_fee_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            investor_fee_bps: source.investor_fee_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            max_ownership_bps: source.max_ownership_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            listing_expiry: source.listing_expiry.into(),
            claiming_time: source.claiming_time.into(),
            claim_deadline: source.claim_deadline.into(),
            legal_process_time: source.legal_process_time.into(),
            lawyer_voting_time: source.lawyer_voting_time.into(),
            min_voting_quorum_bps: source.min_voting_quorum_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            position_count: source.position_count.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            legal_deadline: source.legal_deadline.into(),
            deposit: *source.deposit,
            developer_lawyer: source.developer_lawyer.0,
            spv_lawyer: source.spv_lawyer.0,
            second_attempt: source.second_attempt.into(),
            developer_engaged: source.developer_engaged.into(),
            spv_costs_due: *source.spv_costs_due,
            spv_costs_payee: *source.spv_costs_payee,
            collected_fee_quote: *source.collected_fee_quote,
            collected: source.collected.0,
            spv_election: source.spv_election.0,
            status: source.status.0,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::listing::Listing {
    fn table() -> &'static str {
        "listing_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "listing_id",
            "developer",
            "asset_id",
            "share_price",
            "listed_share_amount",
            "sold_share_amount",
            "reserved_share_amount",
            "tax_paid_by_developer",
            "tax_bps",
            "marketplace_fee_bps",
            "investor_fee_bps",
            "max_ownership_bps",
            "listing_expiry",
            "claiming_time",
            "claim_deadline",
            "legal_process_time",
            "lawyer_voting_time",
            "min_voting_quorum_bps",
            "position_count",
            "legal_deadline",
            "deposit",
            "developer_lawyer",
            "spv_lawyer",
            "second_attempt",
            "developer_engaged",
            "spv_costs_due",
            "spv_costs_payee",
            "collected_fee_quote",
            "collected",
            "spv_election",
            "status",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ListingRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO listing_account (
                "listing_id",
                "developer",
                "asset_id",
                "share_price",
                "listed_share_amount",
                "sold_share_amount",
                "reserved_share_amount",
                "tax_paid_by_developer",
                "tax_bps",
                "marketplace_fee_bps",
                "investor_fee_bps",
                "max_ownership_bps",
                "listing_expiry",
                "claiming_time",
                "claim_deadline",
                "legal_process_time",
                "lawyer_voting_time",
                "min_voting_quorum_bps",
                "position_count",
                "legal_deadline",
                "deposit",
                "developer_lawyer",
                "spv_lawyer",
                "second_attempt",
                "developer_engaged",
                "spv_costs_due",
                "spv_costs_payee",
                "collected_fee_quote",
                "collected",
                "spv_election",
                "status",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34
            )"#)
        .bind(self.listing_id.clone())
        .bind(self.developer.clone())
        .bind(self.asset_id.clone())
        .bind(self.share_price.clone())
        .bind(self.listed_share_amount.clone())
        .bind(self.sold_share_amount.clone())
        .bind(self.reserved_share_amount.clone())
        .bind(self.tax_paid_by_developer.clone())
        .bind(self.tax_bps.clone())
        .bind(self.marketplace_fee_bps.clone())
        .bind(self.investor_fee_bps.clone())
        .bind(self.max_ownership_bps.clone())
        .bind(self.listing_expiry.clone())
        .bind(self.claiming_time.clone())
        .bind(self.claim_deadline.clone())
        .bind(self.legal_process_time.clone())
        .bind(self.lawyer_voting_time.clone())
        .bind(self.min_voting_quorum_bps.clone())
        .bind(self.position_count.clone())
        .bind(self.legal_deadline.clone())
        .bind(self.deposit.clone())
        .bind(self.developer_lawyer.clone())
        .bind(self.spv_lawyer.clone())
        .bind(self.second_attempt.clone())
        .bind(self.developer_engaged.clone())
        .bind(self.spv_costs_due.clone())
        .bind(self.spv_costs_payee.clone())
        .bind(self.collected_fee_quote.clone())
        .bind(self.collected.clone())
        .bind(self.spv_election.clone())
        .bind(self.status.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ListingRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO listing_account (
                "listing_id",
                "developer",
                "asset_id",
                "share_price",
                "listed_share_amount",
                "sold_share_amount",
                "reserved_share_amount",
                "tax_paid_by_developer",
                "tax_bps",
                "marketplace_fee_bps",
                "investor_fee_bps",
                "max_ownership_bps",
                "listing_expiry",
                "claiming_time",
                "claim_deadline",
                "legal_process_time",
                "lawyer_voting_time",
                "min_voting_quorum_bps",
                "position_count",
                "legal_deadline",
                "deposit",
                "developer_lawyer",
                "spv_lawyer",
                "second_attempt",
                "developer_engaged",
                "spv_costs_due",
                "spv_costs_payee",
                "collected_fee_quote",
                "collected",
                "spv_election",
                "status",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "listing_id" = EXCLUDED."listing_id",
                "developer" = EXCLUDED."developer",
                "asset_id" = EXCLUDED."asset_id",
                "share_price" = EXCLUDED."share_price",
                "listed_share_amount" = EXCLUDED."listed_share_amount",
                "sold_share_amount" = EXCLUDED."sold_share_amount",
                "reserved_share_amount" = EXCLUDED."reserved_share_amount",
                "tax_paid_by_developer" = EXCLUDED."tax_paid_by_developer",
                "tax_bps" = EXCLUDED."tax_bps",
                "marketplace_fee_bps" = EXCLUDED."marketplace_fee_bps",
                "investor_fee_bps" = EXCLUDED."investor_fee_bps",
                "max_ownership_bps" = EXCLUDED."max_ownership_bps",
                "listing_expiry" = EXCLUDED."listing_expiry",
                "claiming_time" = EXCLUDED."claiming_time",
                "claim_deadline" = EXCLUDED."claim_deadline",
                "legal_process_time" = EXCLUDED."legal_process_time",
                "lawyer_voting_time" = EXCLUDED."lawyer_voting_time",
                "min_voting_quorum_bps" = EXCLUDED."min_voting_quorum_bps",
                "position_count" = EXCLUDED."position_count",
                "legal_deadline" = EXCLUDED."legal_deadline",
                "deposit" = EXCLUDED."deposit",
                "developer_lawyer" = EXCLUDED."developer_lawyer",
                "spv_lawyer" = EXCLUDED."spv_lawyer",
                "second_attempt" = EXCLUDED."second_attempt",
                "developer_engaged" = EXCLUDED."developer_engaged",
                "spv_costs_due" = EXCLUDED."spv_costs_due",
                "spv_costs_payee" = EXCLUDED."spv_costs_payee",
                "collected_fee_quote" = EXCLUDED."collected_fee_quote",
                "collected" = EXCLUDED."collected",
                "spv_election" = EXCLUDED."spv_election",
                "status" = EXCLUDED."status",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.listing_id.clone())
        .bind(self.developer.clone())
        .bind(self.asset_id.clone())
        .bind(self.share_price.clone())
        .bind(self.listed_share_amount.clone())
        .bind(self.sold_share_amount.clone())
        .bind(self.reserved_share_amount.clone())
        .bind(self.tax_paid_by_developer.clone())
        .bind(self.tax_bps.clone())
        .bind(self.marketplace_fee_bps.clone())
        .bind(self.investor_fee_bps.clone())
        .bind(self.max_ownership_bps.clone())
        .bind(self.listing_expiry.clone())
        .bind(self.claiming_time.clone())
        .bind(self.claim_deadline.clone())
        .bind(self.legal_process_time.clone())
        .bind(self.lawyer_voting_time.clone())
        .bind(self.min_voting_quorum_bps.clone())
        .bind(self.position_count.clone())
        .bind(self.legal_deadline.clone())
        .bind(self.deposit.clone())
        .bind(self.developer_lawyer.clone())
        .bind(self.spv_lawyer.clone())
        .bind(self.second_attempt.clone())
        .bind(self.developer_engaged.clone())
        .bind(self.spv_costs_due.clone())
        .bind(self.spv_costs_payee.clone())
        .bind(self.collected_fee_quote.clone())
        .bind(self.collected.clone())
        .bind(self.spv_election.clone())
        .bind(self.status.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ListingRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM listing_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ListingRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM listing_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ListingMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ListingMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS listing_account (
                -- Account data
                "listing_id" NUMERIC(20) NOT NULL,
                "developer" BYTEA NOT NULL,
                "asset_id" NUMERIC(20) NOT NULL,
                "share_price" NUMERIC(20) NOT NULL,
                "listed_share_amount" INT8 NOT NULL,
                "sold_share_amount" INT8 NOT NULL,
                "reserved_share_amount" INT8 NOT NULL,
                "tax_paid_by_developer" BOOLEAN NOT NULL,
                "tax_bps" INT4 NOT NULL,
                "marketplace_fee_bps" INT4 NOT NULL,
                "investor_fee_bps" INT4 NOT NULL,
                "max_ownership_bps" INT4 NOT NULL,
                "listing_expiry" INT8 NOT NULL,
                "claiming_time" INT8 NOT NULL,
                "claim_deadline" INT8 NOT NULL,
                "legal_process_time" INT8 NOT NULL,
                "lawyer_voting_time" INT8 NOT NULL,
                "min_voting_quorum_bps" INT4 NOT NULL,
                "position_count" INT8 NOT NULL,
                "legal_deadline" INT8 NOT NULL,
                "deposit" NUMERIC(20) NOT NULL,
                "developer_lawyer" JSONB NOT NULL,
                "spv_lawyer" JSONB NOT NULL,
                "second_attempt" BOOLEAN NOT NULL,
                "developer_engaged" BOOLEAN NOT NULL,
                "spv_costs_due" NUMERIC(20) NOT NULL,
                "spv_costs_payee" BYTEA NOT NULL,
                "collected_fee_quote" NUMERIC(20) NOT NULL,
                "collected" JSONB NOT NULL,
                "spv_election" JSONB NOT NULL,
                "status" JSONB NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS listing_account"#).execute(connection).await?;
        Ok(())
    }
}
