//! This code was AUTOGENERATED using the Codama library.
pub mod config_row;
pub mod investor_position_row;
pub mod lawyer_row;
pub mod lawyer_candidacy_row;
pub mod lawyer_vote_row;
pub mod listing_row;
pub mod offer_row;
pub mod property_asset_row;
pub mod reservation_row;
pub mod share_holding_row;
pub mod share_listing_row;

pub use self::config_row::*;
pub use self::investor_position_row::*;
pub use self::lawyer_row::*;
pub use self::lawyer_candidacy_row::*;
pub use self::lawyer_vote_row::*;
pub use self::listing_row::*;
pub use self::offer_row::*;
pub use self::property_asset_row::*;
pub use self::reservation_row::*;
pub use self::share_holding_row::*;
pub use self::share_listing_row::*;

use super::MarketplaceAccount;

pub struct MarketplaceAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for MarketplaceAccountsMigration {
    fn app(&self) -> &str {
        "marketplace"
    }

    fn name(&self) -> &str {
        "marketplace_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(ConfigMigrationOperation),
            Box::new(InvestorPositionMigrationOperation),
            Box::new(LawyerMigrationOperation),
            Box::new(LawyerCandidacyMigrationOperation),
            Box::new(LawyerVoteMigrationOperation),
            Box::new(ListingMigrationOperation),
            Box::new(OfferMigrationOperation),
            Box::new(PropertyAssetMigrationOperation),
            Box::new(ReservationMigrationOperation),
            Box::new(ShareHoldingMigrationOperation),
            Box::new(ShareListingMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct MarketplaceAccountWithMetadata(pub MarketplaceAccount, pub carbon_core::account::AccountMetadata);

impl From<(MarketplaceAccount, carbon_core::account::AccountMetadata)> for MarketplaceAccountWithMetadata {
    fn from(value: (MarketplaceAccount, carbon_core::account::AccountMetadata)) -> Self {
        MarketplaceAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for MarketplaceAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let MarketplaceAccountWithMetadata(account, metadata) = self;

        match account {
            MarketplaceAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::InvestorPosition(account) => {
                let row = investor_position_row::InvestorPositionRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Lawyer(account) => {
                let row = lawyer_row::LawyerRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::LawyerCandidacy(account) => {
                let row = lawyer_candidacy_row::LawyerCandidacyRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::LawyerVote(account) => {
                let row = lawyer_vote_row::LawyerVoteRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Listing(account) => {
                let row = listing_row::ListingRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Offer(account) => {
                let row = offer_row::OfferRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::PropertyAsset(account) => {
                let row = property_asset_row::PropertyAssetRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Reservation(account) => {
                let row = reservation_row::ReservationRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::ShareHolding(account) => {
                let row = share_holding_row::ShareHoldingRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::ShareListing(account) => {
                let row = share_listing_row::ShareListingRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for MarketplaceAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let MarketplaceAccountWithMetadata(account, metadata) = self;
        match account {
            MarketplaceAccount::Config(account) => {
                let row = config_row::ConfigRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::InvestorPosition(account) => {
                let row = investor_position_row::InvestorPositionRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Lawyer(account) => {
                let row = lawyer_row::LawyerRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::LawyerCandidacy(account) => {
                let row = lawyer_candidacy_row::LawyerCandidacyRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::LawyerVote(account) => {
                let row = lawyer_vote_row::LawyerVoteRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Listing(account) => {
                let row = listing_row::ListingRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Offer(account) => {
                let row = offer_row::OfferRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::PropertyAsset(account) => {
                let row = property_asset_row::PropertyAssetRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::Reservation(account) => {
                let row = reservation_row::ReservationRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::ShareHolding(account) => {
                let row = share_holding_row::ShareHoldingRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::ShareListing(account) => {
                let row = share_listing_row::ShareListingRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}

