//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U32;
use carbon_core::postgres::primitives::U64;
use carbon_core::postgres::primitives::U8;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ShareListingRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub id: U64,
    pub asset_id: U64,
    pub seller: Pubkey,
    pub share_price: U64,
    pub amount: U32,
    pub fee_bps: U16,
    pub next_offer_nonce: U64,
    pub rent_payer: Pubkey,
    pub bump: U8,
}

impl ShareListingRow {
    pub fn from_parts(source: crate::accounts::share_listing::ShareListing, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            id: source.id.into(),
            asset_id: source.asset_id.into(),
            seller: source.seller.into(),
            share_price: source.share_price.into(),
            amount: source.amount.into(),
            fee_bps: source.fee_bps.into(),
            next_offer_nonce: source.next_offer_nonce.into(),
            rent_payer: source.rent_payer.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<ShareListingRow> for crate::accounts::share_listing::ShareListing {
    type Error = carbon_core::error::Error;
    fn try_from(source: ShareListingRow) -> Result<Self, Self::Error> {
        Ok(Self {
            id: *source.id,
            asset_id: *source.asset_id,
            seller: *source.seller,
            share_price: *source.share_price,
            amount: source.amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            fee_bps: source.fee_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            next_offer_nonce: *source.next_offer_nonce,
            rent_payer: *source.rent_payer,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::share_listing::ShareListing {
    fn table() -> &'static str {
        "share_listing_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "id",
            "asset_id",
            "seller",
            "share_price",
            "amount",
            "fee_bps",
            "next_offer_nonce",
            "rent_payer",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ShareListingRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO share_listing_account (
                "id",
                "asset_id",
                "seller",
                "share_price",
                "amount",
                "fee_bps",
                "next_offer_nonce",
                "rent_payer",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            )"#)
        .bind(self.id.clone())
        .bind(self.asset_id.clone())
        .bind(self.seller.clone())
        .bind(self.share_price.clone())
        .bind(self.amount.clone())
        .bind(self.fee_bps.clone())
        .bind(self.next_offer_nonce.clone())
        .bind(self.rent_payer.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ShareListingRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO share_listing_account (
                "id",
                "asset_id",
                "seller",
                "share_price",
                "amount",
                "fee_bps",
                "next_offer_nonce",
                "rent_payer",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "id" = EXCLUDED."id",
                "asset_id" = EXCLUDED."asset_id",
                "seller" = EXCLUDED."seller",
                "share_price" = EXCLUDED."share_price",
                "amount" = EXCLUDED."amount",
                "fee_bps" = EXCLUDED."fee_bps",
                "next_offer_nonce" = EXCLUDED."next_offer_nonce",
                "rent_payer" = EXCLUDED."rent_payer",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.id.clone())
        .bind(self.asset_id.clone())
        .bind(self.seller.clone())
        .bind(self.share_price.clone())
        .bind(self.amount.clone())
        .bind(self.fee_bps.clone())
        .bind(self.next_offer_nonce.clone())
        .bind(self.rent_payer.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ShareListingRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM share_listing_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ShareListingRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM share_listing_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ShareListingMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ShareListingMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS share_listing_account (
                -- Account data
                "id" NUMERIC(20) NOT NULL,
                "asset_id" NUMERIC(20) NOT NULL,
                "seller" BYTEA NOT NULL,
                "share_price" NUMERIC(20) NOT NULL,
                "amount" INT8 NOT NULL,
                "fee_bps" INT4 NOT NULL,
                "next_offer_nonce" NUMERIC(20) NOT NULL,
                "rent_payer" BYTEA NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS share_listing_account"#).execute(connection).await?;
        Ok(())
    }
}
