//! This code was AUTOGENERATED using the Codama library.
use juniper::{graphql_object, FieldResult};
use std::str::FromStr;

pub struct QueryRoot;

#[graphql_object(context = crate::graphql::context::GraphQLContext)]
impl QueryRoot {
    // Accounts
    async fn config(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::ConfigGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::ConfigRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_config(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::ConfigGraphQL>> {
        let rows: Vec<crate::accounts::postgres::ConfigRow> = sqlx::query_as(
            r#"SELECT * FROM config_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn location(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::LocationGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::LocationRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_location(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::LocationGraphQL>> {
        let rows: Vec<crate::accounts::postgres::LocationRow> = sqlx::query_as(
            r#"SELECT * FROM location_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn region(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::RegionGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::RegionRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_region(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::RegionGraphQL>> {
        let rows: Vec<crate::accounts::postgres::RegionRow> = sqlx::query_as(
            r#"SELECT * FROM region_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::RegionProposalGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::RegionProposalRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::RegionProposalGraphQL>> {
        let rows: Vec<crate::accounts::postgres::RegionProposalRow> = sqlx::query_as(
            r#"SELECT * FROM region_proposal_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn region_state(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::RegionStateGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::RegionStateRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_region_state(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::RegionStateGraphQL>> {
        let rows: Vec<crate::accounts::postgres::RegionStateRow> = sqlx::query_as(
            r#"SELECT * FROM region_state_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn vote_record(
        context: &crate::graphql::context::GraphQLContext,
        pubkey: String,
    ) -> FieldResult<Option<crate::accounts::graphql::VoteRecordGraphQL>> {
        use carbon_core::postgres::operations::LookUp;
        use carbon_core::postgres::primitives::Pubkey as PgPubkey;
        let pk = PgPubkey(solana_pubkey::Pubkey::from_str(&pubkey).map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?);
        let row = crate::accounts::postgres::VoteRecordRow::lookup(pk, &context.pool).await
            .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(row.map(|row| row.try_into().ok()).flatten())
    }

    async fn list_vote_record(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::accounts::graphql::VoteRecordGraphQL>> {
        let rows: Vec<crate::accounts::postgres::VoteRecordRow> = sqlx::query_as(
            r#"SELECT * FROM vote_record_account ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    // Instructions (per-instruction list and lookup by signature+index)
    async fn adjust_listing_duration(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::AdjustListingDurationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::AdjustListingDurationRow> = sqlx::query_as(
            r#"SELECT * FROM adjust_listing_duration_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_adjust_listing_duration(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::AdjustListingDurationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::AdjustListingDurationRow> = sqlx::query_as(
            r#"SELECT * FROM adjust_listing_duration_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn adjust_region_tax(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::AdjustRegionTaxGraphQL>> {
        let rows: Vec<crate::instructions::postgres::AdjustRegionTaxRow> = sqlx::query_as(
            r#"SELECT * FROM adjust_region_tax_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_adjust_region_tax(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::AdjustRegionTaxGraphQL>> {
        let rows: Vec<crate::instructions::postgres::AdjustRegionTaxRow> = sqlx::query_as(
            r#"SELECT * FROM adjust_region_tax_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn claim_open_region(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ClaimOpenRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ClaimOpenRegionRow> = sqlx::query_as(
            r#"SELECT * FROM claim_open_region_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_claim_open_region(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ClaimOpenRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ClaimOpenRegionRow> = sqlx::query_as(
            r#"SELECT * FROM claim_open_region_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn clear_region_state(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ClearRegionStateGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ClearRegionStateRow> = sqlx::query_as(
            r#"SELECT * FROM clear_region_state_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_clear_region_state(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ClearRegionStateGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ClearRegionStateRow> = sqlx::query_as(
            r#"SELECT * FROM clear_region_state_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn create_new_location(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::CreateNewLocationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::CreateNewLocationRow> = sqlx::query_as(
            r#"SELECT * FROM create_new_location_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_create_new_location(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::CreateNewLocationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::CreateNewLocationRow> = sqlx::query_as(
            r#"SELECT * FROM create_new_location_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn create_region(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::CreateRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::CreateRegionRow> = sqlx::query_as(
            r#"SELECT * FROM create_region_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_create_region(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::CreateRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::CreateRegionRow> = sqlx::query_as(
            r#"SELECT * FROM create_region_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn finalize_region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::FinalizeRegionProposalGraphQL>> {
        let rows: Vec<crate::instructions::postgres::FinalizeRegionProposalRow> = sqlx::query_as(
            r#"SELECT * FROM finalize_region_proposal_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_finalize_region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::FinalizeRegionProposalGraphQL>> {
        let rows: Vec<crate::instructions::postgres::FinalizeRegionProposalRow> = sqlx::query_as(
            r#"SELECT * FROM finalize_region_proposal_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn initialize_config(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::InitializeConfigGraphQL>> {
        let rows: Vec<crate::instructions::postgres::InitializeConfigRow> = sqlx::query_as(
            r#"SELECT * FROM initialize_config_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_initialize_config(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::InitializeConfigGraphQL>> {
        let rows: Vec<crate::instructions::postgres::InitializeConfigRow> = sqlx::query_as(
            r#"SELECT * FROM initialize_config_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn initiate_resignation(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::InitiateResignationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::InitiateResignationRow> = sqlx::query_as(
            r#"SELECT * FROM initiate_resignation_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_initiate_resignation(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::InitiateResignationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::InitiateResignationRow> = sqlx::query_as(
            r#"SELECT * FROM initiate_resignation_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn propose_new_region(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ProposeNewRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ProposeNewRegionRow> = sqlx::query_as(
            r#"SELECT * FROM propose_new_region_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_propose_new_region(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::ProposeNewRegionGraphQL>> {
        let rows: Vec<crate::instructions::postgres::ProposeNewRegionRow> = sqlx::query_as(
            r#"SELECT * FROM propose_new_region_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn remove_location(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::RemoveLocationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::RemoveLocationRow> = sqlx::query_as(
            r#"SELECT * FROM remove_location_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_remove_location(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::RemoveLocationGraphQL>> {
        let rows: Vec<crate::instructions::postgres::RemoveLocationRow> = sqlx::query_as(
            r#"SELECT * FROM remove_location_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn unlock_voting_token(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UnlockVotingTokenGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UnlockVotingTokenRow> = sqlx::query_as(
            r#"SELECT * FROM unlock_voting_token_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_unlock_voting_token(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UnlockVotingTokenGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UnlockVotingTokenRow> = sqlx::query_as(
            r#"SELECT * FROM unlock_voting_token_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn update_authority(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UpdateAuthorityGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UpdateAuthorityRow> = sqlx::query_as(
            r#"SELECT * FROM update_authority_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_update_authority(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UpdateAuthorityGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UpdateAuthorityRow> = sqlx::query_as(
            r#"SELECT * FROM update_authority_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn update_config(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UpdateConfigGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UpdateConfigRow> = sqlx::query_as(
            r#"SELECT * FROM update_config_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_update_config(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::UpdateConfigGraphQL>> {
        let rows: Vec<crate::instructions::postgres::UpdateConfigRow> = sqlx::query_as(
            r#"SELECT * FROM update_config_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn vote_on_region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        signature: String,
        instruction_index: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::VoteOnRegionProposalGraphQL>> {
        let rows: Vec<crate::instructions::postgres::VoteOnRegionProposalRow> = sqlx::query_as(
            r#"SELECT * FROM vote_on_region_proposal_instruction WHERE __signature = $1 AND __instruction_index = $2 ORDER BY __stack_height ASC"#,
        )
        .bind(signature)
        .bind(instruction_index)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_vote_on_region_proposal(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::VoteOnRegionProposalGraphQL>> {
        let rows: Vec<crate::instructions::postgres::VoteOnRegionProposalRow> = sqlx::query_as(
            r#"SELECT * FROM vote_on_region_proposal_instruction ORDER BY __slot DESC, __signature DESC, __instruction_index ASC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }

    async fn list_cpi_events(
        context: &crate::graphql::context::GraphQLContext,
        limit: i32,
        offset: i32,
    ) -> FieldResult<Vec<crate::instructions::graphql::CpiEventGraphQL>> {
        let rows: Vec<crate::instructions::postgres::CpiEventRow> = sqlx::query_as(
            r#"SELECT * FROM cpi_events ORDER BY __slot DESC LIMIT $1 OFFSET $2"#,
        )
        .bind(limit)
        .bind(offset)
        .fetch_all(&*context.pool)
        .await
        .map_err(|e| juniper::FieldError::new(e.to_string(), juniper::Value::null()))?;
        Ok(rows.into_iter().filter_map(|row| row.try_into().ok()).collect())
    }
}
