//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CloseIncomeCheckpoint")]
pub struct CloseIncomeCheckpointGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub asset_id: U64,
}

impl TryFrom<crate::instructions::postgres::CloseIncomeCheckpointRow> for CloseIncomeCheckpointGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::CloseIncomeCheckpointRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
        })
    }
}
