//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UnlockChallengeVotes")]
pub struct UnlockChallengeVotesGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub asset_id: U64,
    pub id: U64,
}

impl TryFrom<crate::instructions::postgres::UnlockChallengeVotesRow> for UnlockChallengeVotesGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::UnlockChallengeVotesRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            asset_id: carbon_core::graphql::primitives::U64(*row.asset_id),
            id: carbon_core::graphql::primitives::U64(*row.id),
        })
    }
}
