//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ChallengeAgentRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub asset_id: U64,
    pub id: U64,
    pub max_deposit: U64,
}

impl ChallengeAgentRow {
    pub fn from_parts(source: crate::instructions::challenge_agent::ChallengeAgent, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            asset_id: source.asset_id.into(),
            id: source.id.into(),
            max_deposit: source.max_deposit.into(),
        }
    }
}

impl TryFrom<ChallengeAgentRow> for crate::instructions::challenge_agent::ChallengeAgent {
    type Error = carbon_core::error::Error;
    fn try_from(source: ChallengeAgentRow) -> Result<Self, Self::Error> {
        Ok(Self {
            asset_id: *source.asset_id,
            id: *source.id,
            max_deposit: *source.max_deposit,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::challenge_agent::ChallengeAgent {
    fn table() -> &'static str {
        "challenge_agent_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "asset_id",
            "id",
            "max_deposit",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ChallengeAgentRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO challenge_agent_instruction (
                "asset_id",
                "id",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.asset_id.clone())
        .bind(self.id.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ChallengeAgentRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO challenge_agent_instruction (
                "asset_id",
                "id",
                "max_deposit",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "asset_id" = EXCLUDED."asset_id",
                "id" = EXCLUDED."id",
                "max_deposit" = EXCLUDED."max_deposit",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.asset_id.clone())
        .bind(self.id.clone())
        .bind(self.max_deposit.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ChallengeAgentRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM challenge_agent_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ChallengeAgentRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM challenge_agent_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ChallengeAgentMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ChallengeAgentMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS challenge_agent_instruction (
                -- Instruction data
                "asset_id" NUMERIC(20) NOT NULL,
                "id" NUMERIC(20) NOT NULL,
                "max_deposit" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS challenge_agent_instruction"#).execute(connection).await?;
        Ok(())
    }
}
