//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct RemoveLettingAgentRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub postcode: Vec<u8>,
}

impl RemoveLettingAgentRow {
    pub fn from_parts(source: crate::instructions::remove_letting_agent::RemoveLettingAgent, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            postcode: source.postcode.into(),
        }
    }
}

impl TryFrom<RemoveLettingAgentRow> for crate::instructions::remove_letting_agent::RemoveLettingAgent {
    type Error = carbon_core::error::Error;
    fn try_from(source: RemoveLettingAgentRow) -> Result<Self, Self::Error> {
        Ok(Self {
            postcode: source.postcode.into(),
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::remove_letting_agent::RemoveLettingAgent {
    fn table() -> &'static str {
        "remove_letting_agent_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "postcode",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RemoveLettingAgentRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO remove_letting_agent_instruction (
                "postcode",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            )"#)
        .bind(self.postcode.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RemoveLettingAgentRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO remove_letting_agent_instruction (
                "postcode",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "postcode" = EXCLUDED."postcode",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.postcode.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for RemoveLettingAgentRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM remove_letting_agent_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for RemoveLettingAgentRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM remove_letting_agent_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct RemoveLettingAgentMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for RemoveLettingAgentMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS remove_letting_agent_instruction (
                -- Instruction data
                "postcode" BYTEA NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS remove_letting_agent_instruction"#).execute(connection).await?;
        Ok(())
    }
}
