//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U32;
use carbon_core::postgres::primitives::U64;
use crate::types::VoteChoice;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct VoteOnProposalRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub asset_id: U64,
    pub choice: sqlx::types::Json<VoteChoice>,
    pub amount: U32,
}

impl VoteOnProposalRow {
    pub fn from_parts(source: crate::instructions::vote_on_proposal::VoteOnProposal, metadata: InstructionMetadata) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            asset_id: source.asset_id.into(),
            choice: sqlx::types::Json(source.choice.into()),
            amount: source.amount.into(),
        }
    }
}

impl TryFrom<VoteOnProposalRow> for crate::instructions::vote_on_proposal::VoteOnProposal {
    type Error = carbon_core::error::Error;
    fn try_from(source: VoteOnProposalRow) -> Result<Self, Self::Error> {
        Ok(Self {
            asset_id: *source.asset_id,
            choice: source.choice.0,
            amount: source.amount.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::vote_on_proposal::VoteOnProposal {
    fn table() -> &'static str {
        "vote_on_proposal_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "asset_id",
            "choice",
            "amount",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for VoteOnProposalRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO vote_on_proposal_instruction (
                "asset_id",
                "choice",
                "amount",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#)
        .bind(self.asset_id.clone())
        .bind(self.choice.clone())
        .bind(self.amount.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for VoteOnProposalRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO vote_on_proposal_instruction (
                "asset_id",
                "choice",
                "amount",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "asset_id" = EXCLUDED."asset_id",
                "choice" = EXCLUDED."choice",
                "amount" = EXCLUDED."amount",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.asset_id.clone())
        .bind(self.choice.clone())
        .bind(self.amount.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for VoteOnProposalRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM vote_on_proposal_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for VoteOnProposalRow {
    type Key = (String, carbon_core::postgres::primitives::U32, carbon_core::postgres::primitives::U32);

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM vote_on_proposal_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#)
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct VoteOnProposalMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for VoteOnProposalMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS vote_on_proposal_instruction (
                -- Instruction data
                "asset_id" NUMERIC(20) NOT NULL,
                "choice" JSONB NOT NULL,
                "amount" INT8 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS vote_on_proposal_instruction"#).execute(connection).await?;
        Ok(())
    }
}
